'use client'

import { AlertTriangle, Info, X } from 'lucide-react'
import { useState } from 'react'

export function AIDisclaimer() {
  const [isExpanded, setIsExpanded] = useState(false)
  const [isDismissed, setIsDismissed] = useState(false)

  if (isDismissed) {
    return null
  }

  return (
    <aside
      className="absolute bottom-4 right-4 z-30 w-[min(32rem,calc(100%-2rem))] rounded-xl border border-amber-200 bg-amber-50/95 p-3 shadow-xl shadow-slate-900/15 backdrop-blur dark:border-amber-400/30 dark:bg-amber-950/90 dark:shadow-black/30"
      aria-label="Generated legal analysis notice"
      role="region"
    >
      <div className="flex items-start gap-3">
        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-200">
          <AlertTriangle className="h-4 w-4" aria-hidden="true" />
        </div>

        <div className="min-w-0 flex-1">
          <div className="flex items-start justify-between gap-3">
            <div>
              <h3 className="font-display text-sm font-semibold text-amber-950 dark:text-amber-100">
                Generated Legal Analysis
              </h3>
              <p className="font-body mt-1 text-xs leading-5 text-amber-800 dark:text-amber-200">
                Informational only. Not legal advice.
              </p>
            </div>

            <button
              onClick={() => setIsDismissed(true)}
              className="rounded-md p-1 text-amber-700 transition-colors hover:bg-amber-100 hover:text-amber-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-2 focus-visible:ring-offset-amber-50 dark:text-amber-200 dark:hover:bg-amber-400/15 dark:hover:text-amber-50 dark:focus-visible:ring-offset-amber-950"
              aria-label="Dismiss legal analysis notice"
              type="button"
            >
              <X className="h-4 w-4" aria-hidden="true" />
            </button>
          </div>

          {isExpanded && (
            <p className="font-body mt-2 text-xs leading-5 text-amber-800 dark:text-amber-200">
              This analysis may be AI-assisted or generated by local providerless rules. It is informational only and is not legal advice.
            </p>
          )}

          <div className="mt-2">
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="text-xs font-semibold text-amber-700 underline underline-offset-2 hover:text-amber-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-2 focus-visible:ring-offset-amber-50 dark:text-amber-200 dark:hover:text-amber-50 dark:focus-visible:ring-offset-amber-950"
              aria-expanded={isExpanded}
              type="button"
            >
              {isExpanded ? 'Show less' : 'Read full disclaimer'}
            </button>
          </div>

          {isExpanded && (
            <div className="mt-3 max-h-64 space-y-2 overflow-y-auto border-t border-amber-200 pt-3 text-xs leading-5 text-amber-800 dark:border-amber-400/30 dark:text-amber-200">
              <p className="font-medium">This tool is NOT a substitute for:</p>
              <ul className="ml-2 list-inside list-disc space-y-1">
                <li>Professional legal advice from licensed attorneys</li>
                <li>Official compliance audits by government agencies</li>
                <li>Consultation with certified compliance experts</li>
                <li>Formal validation by relevant government offices</li>
              </ul>

              <p className="mt-3 font-medium">Users are strongly advised to:</p>
              <ul className="ml-2 list-inside list-disc space-y-1">
                <li>Verify all findings with official government sources</li>
                <li>Consult with legal counsel before making compliance decisions</li>
                <li>Submit documents to proper authorities for official review</li>
                <li>Seek guidance from relevant regulatory agencies</li>
              </ul>

              <div className="mt-3 rounded border border-amber-300 bg-amber-100 p-2 dark:border-amber-400/30 dark:bg-amber-400/10">
                <p className="font-semibold">Limitation of Liability</p>
                <p className="mt-1">
                  The creators and operators of LexInSight assume no liability for decisions made based on this analysis.
                  Users bear full responsibility for ensuring compliance with all applicable laws and regulations.
                </p>
              </div>

              <p className="mt-3 text-center italic">
                Always seek professional legal counsel for critical compliance decisions.
              </p>
            </div>
          )}
        </div>
      </div>
    </aside>
  )
}

export function AIDisclaimerBadge() {
  return (
    <div className="inline-flex items-center gap-1.5 rounded border border-amber-200 bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800 dark:border-amber-400/30 dark:bg-amber-400/10 dark:text-amber-200">
      <Info className="h-3 w-3" aria-hidden="true" />
      <span>Generated - Not Legal Advice</span>
    </div>
  )
}
