'use client'

import { AlertTriangle, Info, X } from 'lucide-react'
import { useState } from 'react'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'

export function AIDisclaimer() {
  const [isDialogOpen, setIsDialogOpen] = useState(false)
  const [isDismissed, setIsDismissed] = useState(false)

  if (isDismissed) {
    return null
  }

  return (
    <>
      <aside
        className="absolute bottom-4 right-4 z-30 w-[min(32rem,calc(100%-2rem))] rounded-xl border border-amber-200 bg-amber-50/95 p-3 shadow-xl shadow-slate-900/15 backdrop-blur dark:border-amber-400/30 dark:bg-amber-950/90 dark:shadow-iris-950/30"
        aria-label="Generated legal analysis notice"
        role="region"
      >
        <div className="flex items-start gap-3">
          <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-200">
            <AlertTriangle className="h-4 w-4" aria-hidden="true" />
          </div>

          <div className="min-w-0 flex-1">
            <div className="flex items-start justify-between gap-3">
              <div>
                <h3 className="font-display text-sm font-semibold text-amber-950 dark:text-amber-100">
                  Generated Legal Analysis
                </h3>
                <p className="font-body mt-1 text-xs leading-5 text-amber-800 dark:text-amber-200">
                  Informational only. Not legal advice.
                </p>
              </div>

              <button
                onClick={() => setIsDismissed(true)}
                className="rounded-md p-1 text-amber-700 transition-colors hover:bg-amber-100 hover:text-amber-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-2 focus-visible:ring-offset-amber-50 dark:text-amber-200 dark:hover:bg-amber-400/15 dark:hover:text-amber-50 dark:focus-visible:ring-offset-amber-950"
                aria-label="Dismiss legal analysis notice"
                type="button"
              >
                <X className="h-4 w-4" aria-hidden="true" />
              </button>
            </div>

            <div className="mt-2">
              <button
                onClick={() => setIsDialogOpen(true)}
                className="text-xs font-semibold text-amber-700 underline underline-offset-2 hover:text-amber-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 focus-visible:ring-offset-2 focus-visible:ring-offset-amber-50 dark:text-amber-200 dark:hover:text-amber-50 dark:focus-visible:ring-offset-amber-950"
                aria-haspopup="dialog"
                type="button"
              >
                Read full disclaimer
              </button>
            </div>
          </div>
        </div>
      </aside>

      <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
        <DialogContent className="max-h-[88dvh] max-w-[calc(100vw-1rem)] gap-0 overflow-hidden border-amber-200 bg-white p-0 shadow-2xl dark:border-amber-400/25 dark:bg-[#171322] sm:max-w-2xl">
          <DialogHeader className="border-b border-amber-200 bg-amber-50 px-5 py-5 pr-12 dark:border-amber-400/25 dark:bg-amber-400/10">
            <div className="flex items-start gap-3">
              <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-700 dark:bg-amber-400/15 dark:text-amber-200">
                <AlertTriangle className="h-5 w-5" aria-hidden="true" />
              </div>
              <div className="min-w-0">
                <DialogTitle className="text-xl font-bold leading-tight text-amber-950 dark:text-amber-100">
                  Generated Legal Analysis
                </DialogTitle>
                <DialogDescription className="mt-2 text-sm leading-6 text-amber-800 dark:text-amber-200">
                  This analysis may be AI-assisted or generated by local providerless rules. It is informational only and is not legal advice.
                </DialogDescription>
              </div>
            </div>
          </DialogHeader>

          <div className="min-h-0 overflow-y-auto px-5 py-5 text-sm leading-6 text-slate-700 dark:text-slate-300">
            <section aria-labelledby="disclaimer-substitutes">
              <h4 id="disclaimer-substitutes" className="font-display text-base font-bold text-slate-950 dark:text-slate-100">
                This tool is not a substitute for
              </h4>
              <ul className="mt-3 list-disc space-y-2 pl-5">
                <li>Professional legal advice from licensed attorneys</li>
                <li>Official compliance audits by government agencies</li>
                <li>Consultation with certified compliance experts</li>
                <li>Formal validation by relevant government offices</li>
              </ul>
            </section>

            <section className="mt-6 border-t border-slate-200 pt-5 dark:border-iris-300/15" aria-labelledby="disclaimer-actions">
              <h4 id="disclaimer-actions" className="font-display text-base font-bold text-slate-950 dark:text-slate-100">
                Users are strongly advised to
              </h4>
              <ul className="mt-3 list-disc space-y-2 pl-5">
                <li>Verify all findings with official government sources</li>
                <li>Consult with legal counsel before making compliance decisions</li>
                <li>Submit documents to proper authorities for official review</li>
                <li>Seek guidance from relevant regulatory agencies</li>
              </ul>
            </section>

            <section className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-400/25 dark:bg-amber-400/10" aria-labelledby="disclaimer-liability">
              <h4 id="disclaimer-liability" className="font-display text-base font-bold text-amber-950 dark:text-amber-100">
                Limitation of liability
              </h4>
              <p className="mt-2 text-amber-800 dark:text-amber-200">
                The creators and operators of LexInSight assume no liability for decisions made based on this analysis.
                Users bear full responsibility for ensuring compliance with all applicable laws and regulations.
              </p>
            </section>
          </div>

          <DialogFooter className="border-t border-slate-200 bg-slate-50 px-5 py-4 dark:border-iris-300/15 dark:bg-[#1a1625]">
            <p className="min-w-0 flex-1 text-xs leading-5 text-slate-500 dark:text-slate-400">
              Always seek professional legal counsel for critical compliance decisions.
            </p>
            <DialogClose className="inline-flex h-10 cursor-pointer items-center justify-center rounded-lg bg-iris-600 px-4 text-sm font-semibold text-white transition-colors hover:bg-iris-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-iris-400 focus-visible:ring-offset-2 dark:focus-visible:ring-offset-[#171322]">
              I understand
            </DialogClose>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  )
}

export function AIDisclaimerBadge() {
  return (
    <div className="inline-flex items-center gap-1.5 rounded border border-amber-200 bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800 dark:border-amber-400/30 dark:bg-amber-400/10 dark:text-amber-200">
      <Info className="h-3 w-3" aria-hidden="true" />
      <span>Generated - Not Legal Advice</span>
    </div>
  )
}
