'use client'

import { AlertTriangle, Info } from 'lucide-react'
import { useState } from 'react'

export function AIDisclaimer() {
  const [isExpanded, setIsExpanded] = useState(false)

  return (
    <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3">
      <div className="flex items-start gap-2">
        <AlertTriangle className="mt-0.5 h-5 w-5 flex-shrink-0 text-amber-600" aria-hidden="true" />
        <div className="flex-1">
          <div className="flex items-center justify-between gap-3">
            <h3 className="font-display text-sm font-semibold text-amber-900">
              Generated Legal Analysis
            </h3>
            <button
              onClick={() => setIsExpanded(!isExpanded)}
              className="text-xs font-medium text-amber-700 underline hover:text-amber-900"
              aria-expanded={isExpanded}
            >
              {isExpanded ? 'Show less' : 'Read full disclaimer'}
            </button>
          </div>

          <p className="font-body mt-1 text-xs text-amber-800">
            This analysis may be AI-assisted or generated by local providerless rules. It is informational only and is not legal advice.
          </p>

          {isExpanded && (
            <div className="mt-3 space-y-2 border-t border-amber-200 pt-3 text-xs text-amber-800">
              <p className="font-medium">This tool is NOT a substitute for:</p>
              <ul className="ml-2 list-inside list-disc space-y-1">
                <li>Professional legal advice from licensed attorneys</li>
                <li>Official compliance audits by government agencies</li>
                <li>Consultation with certified compliance experts</li>
                <li>Formal validation by relevant government offices</li>
              </ul>

              <p className="mt-3 font-medium">Users are strongly advised to:</p>
              <ul className="ml-2 list-inside list-disc space-y-1">
                <li>Verify all findings with official government sources</li>
                <li>Consult with legal counsel before making compliance decisions</li>
                <li>Submit documents to proper authorities for official review</li>
                <li>Seek guidance from relevant regulatory agencies</li>
              </ul>

              <div className="mt-3 rounded border border-amber-300 bg-amber-100 p-2">
                <p className="font-semibold">Limitation of Liability</p>
                <p className="mt-1">
                  The creators and operators of LexInSight assume no liability for decisions made based on this analysis.
                  Users bear full responsibility for ensuring compliance with all applicable laws and regulations.
                </p>
              </div>

              <p className="mt-3 text-center italic">
                Always seek professional legal counsel for critical compliance decisions.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export function AIDisclaimerBadge() {
  return (
    <div className="inline-flex items-center gap-1.5 rounded border border-amber-200 bg-amber-100 px-2 py-1 text-xs font-medium text-amber-800">
      <Info className="h-3 w-3" aria-hidden="true" />
      <span>Generated - Not Legal Advice</span>
    </div>
  )
}
