import { COMPLIANCE_FRAMEWORKS } from './compliance-frameworks'
import type { LocalAuthorityRelation } from './types'

const CURATED_RELATIONS: LocalAuthorityRelation[] = [
  {
    sourceId: 'npc-advisory-2024-04',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC advisory guidance for Data Privacy Act governance',
    weight: 1.2,
  },
  {
    sourceId: 'sc-ai-governance-framework-2026',
    targetId: 'ra-10173',
    type: 'cross_references',
    label: 'AI governance privacy safeguards',
    weight: 1,
  },
  {
    sourceId: 'ra-11930',
    targetId: 'ra-9775',
    type: 'amends',
    label: 'OSAEC/CSAEM amendments to online child-protection framework',
    weight: 1.3,
  },
  {
    sourceId: 'ra-10172',
    targetId: 'ra-9048',
    type: 'amends',
    label: 'Civil registry correction expansion',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10022',
    targetId: 'ra-8042',
    type: 'amends',
    label: 'Migrant worker protection amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11211',
    targetId: 'ra-7653',
    type: 'amends',
    label: 'BSP charter amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11898',
    targetId: 'ra-9003',
    type: 'amends',
    label: 'EPR Act amendments to ecological solid waste framework',
    weight: 1.2,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-7653',
    type: 'workflow_related_to',
    label: 'Payment-system supervision under BSP charter',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-11211',
    type: 'workflow_related_to',
    label: 'Payment systems and BSP financial-stability powers',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-9160',
    type: 'workflow_related_to',
    label: 'Payment-system operations and AML monitoring coordination',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10168',
    type: 'workflow_related_to',
    label: 'Payment rails and CFT screening coordination',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-8484',
    type: 'workflow_related_to',
    label: 'Payment systems and access-device fraud evidence',
    weight: 1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-12010',
    type: 'workflow_related_to',
    label: 'Payment systems and financial-account scam handling',
    weight: 1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-11765',
    type: 'workflow_related_to',
    label: 'Payment services and financial-consumer complaint handling',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10175',
    type: 'workflow_related_to',
    label: 'Payment platforms and cybercrime evidence coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10173',
    type: 'workflow_related_to',
    label: 'Payment-system records privacy safeguards',
    weight: 0.95,
  },
  {
    sourceId: 'ra-10168',
    targetId: 'ra-9160',
    type: 'cross_references',
    label: 'CFT controls share AMLC reporting framework',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10168',
    targetId: 'ra-11479',
    type: 'workflow_related_to',
    label: 'CFT asset-freeze and anti-terrorism designation coordination',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-10173',
    type: 'workflow_related_to',
    label: 'Anti-terrorism watchlist and incident records privacy safeguards',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-10175',
    type: 'workflow_related_to',
    label: 'Anti-terrorism referrals and cybercrime evidence coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-4200',
    type: 'cross_references',
    label: 'Surveillance and communications-interception safeguards',
    weight: 1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'constitution-1987',
    type: 'requires',
    label: 'Bill of Rights due-process safeguards for anti-terrorism actions',
    weight: 1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'rules-criminal-procedure',
    type: 'workflow_related_to',
    label: 'Criminal procedure safeguards for anti-terrorism enforcement',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-9745',
    type: 'workflow_related_to',
    label: 'Custodial and human-rights safeguards for detention or interrogation',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11647',
    targetId: 'ra-7042',
    type: 'amends',
    label: 'Foreign investment liberalization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11595',
    targetId: 'ra-8762',
    type: 'amends',
    label: 'Retail trade liberalization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-12021',
    targetId: 'ra-10635',
    type: 'cross_references',
    label: 'Seafarer welfare and STCW credential relationship',
    weight: 1,
  },
  {
    sourceId: 'ra-9295',
    targetId: 'ra-9993',
    type: 'workflow_related_to',
    label: 'Domestic shipping safety and Coast Guard incident coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-9295',
    targetId: 'pd-857',
    type: 'workflow_related_to',
    label: 'Domestic shipping and port-operation coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'Downstream oil market monitoring under DOE energy mandate',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'LPG industry regulation and DOE energy oversight',
    weight: 1.1,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'Biofuels program and DOE energy policy coordination',
    weight: 1.1,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-8479',
    type: 'workflow_related_to',
    label: 'Biofuel blends in downstream petroleum product workflows',
    weight: 1,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-8479',
    type: 'workflow_related_to',
    label: 'LPG retail and refilling within downstream fuel controls',
    weight: 0.95,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-7394',
    type: 'workflow_related_to',
    label: 'Fuel retail consumer complaint and product-disclosure coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-7394',
    type: 'workflow_related_to',
    label: 'LPG product safety and consumer complaint coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-9513',
    type: 'workflow_related_to',
    label: 'Biofuels and renewable-energy policy relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-10667',
    type: 'workflow_related_to',
    label: 'Deregulated downstream oil market and competition-risk review',
    weight: 0.85,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'pd-1586',
    type: 'workflow_related_to',
    label: 'Fuel facilities and environmental impact screening coordination',
    weight: 0.85,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-8749',
    type: 'workflow_related_to',
    label: 'Biofuel blend claims and air-quality coordination',
    weight: 0.85,
  },
  {
    sourceId: 'ra-9369',
    targetId: 'ra-8436',
    type: 'amends',
    label: 'Automated election modernization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-10930',
    targetId: 'ra-4136',
    type: 'amends',
    label: 'Driver license validity amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-11976',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'Ease of Paying Taxes updates to the tax code',
    weight: 1,
  },
  {
    sourceId: 'ra-10963',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'TRAIN tax code amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-11534',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'CREATE tax code amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-12066',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'CREATE MORE tax incentive updates',
    weight: 1,
  },
  {
    sourceId: 'eo-209-1987',
    targetId: 'ra-386',
    type: 'cross_references',
    label: 'Family Code and Civil Code private-law relationship',
    weight: 0.9,
  },
]

const FRAMEWORK_RELATIONS: LocalAuthorityRelation[] = COMPLIANCE_FRAMEWORKS.flatMap((framework) => (
  framework.lawIds.flatMap((sourceId) => (
    framework.lawIds
      .filter((targetId) => targetId !== sourceId)
      .map((targetId) => ({
        sourceId,
        targetId,
        type: 'workflow_related_to' as const,
        label: framework.title,
        weight: 0.45,
      }))
  ))
))

function relationKey(relation: LocalAuthorityRelation) {
  return `${relation.sourceId}:${relation.type}:${relation.targetId}:${relation.label}`
}

export const AUTHORITY_RELATIONS: LocalAuthorityRelation[] = [
  ...CURATED_RELATIONS,
  ...FRAMEWORK_RELATIONS,
].filter((relation, index, relations) => (
  relations.findIndex((candidate) => relationKey(candidate) === relationKey(relation)) === index
))
