import { COMPLIANCE_FRAMEWORKS } from './compliance-frameworks'
import type { LocalAuthorityRelation } from './types'

const CURATED_RELATIONS: LocalAuthorityRelation[] = [
  {
    sourceId: 'npc-advisory-2024-04',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC advisory guidance for Data Privacy Act governance',
    weight: 1.2,
  },
  {
    sourceId: 'npc-circular-16-03',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC breach-management guidance for Data Privacy Act compliance',
    weight: 1.2,
  },
  {
    sourceId: 'npc-advisory-2026-02',
    targetId: 'npc-circular-16-03',
    type: 'workflow_related_to',
    label: 'DBNMS submission guidance for personal data breach notification',
    weight: 1.1,
  },
  {
    sourceId: 'npc-circular-2023-06',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC personal-data security guidance for Data Privacy Act compliance',
    weight: 1.2,
  },
  {
    sourceId: 'npc-circular-2023-04',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC consent guidance for Data Privacy Act compliance',
    weight: 1.15,
  },
  {
    sourceId: 'npc-circular-2022-04',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC processing-system registration and DPO guidance for Data Privacy Act compliance',
    weight: 1.15,
  },
  {
    sourceId: 'npc-circular-2020-03',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC data-sharing agreement guidance for Data Privacy Act compliance',
    weight: 1.15,
  },
  {
    sourceId: 'npc-advisory-2025-02',
    targetId: 'ra-10173',
    type: 'agency_guidance_for',
    label: 'NPC privacy-engineering guidance for Data Privacy Act compliance',
    weight: 1.1,
  },
  {
    sourceId: 'npc-advisory-2025-02',
    targetId: 'npc-advisory-2024-04',
    type: 'workflow_related_to',
    label: 'Privacy engineering and AI privacy governance relationship',
    weight: 1,
  },
  {
    sourceId: 'npc-circular-2023-06',
    targetId: 'npc-circular-16-03',
    type: 'workflow_related_to',
    label: 'Personal-data security and breach-management relationship',
    weight: 1,
  },
  {
    sourceId: 'npc-circular-2020-03',
    targetId: 'npc-circular-2023-04',
    type: 'workflow_related_to',
    label: 'Data sharing and consent governance relationship',
    weight: 0.95,
  },
  {
    sourceId: 'sc-ai-governance-framework-2026',
    targetId: 'ra-10173',
    type: 'cross_references',
    label: 'AI governance privacy safeguards',
    weight: 1,
  },
  {
    sourceId: 'ra-11930',
    targetId: 'ra-9775',
    type: 'amends',
    label: 'OSAEC/CSAEM amendments to online child-protection framework',
    weight: 1.3,
  },
  {
    sourceId: 'ra-9442',
    targetId: 'ra-7277',
    type: 'amends',
    label: 'PWD privileges and anti-discrimination amendments to Magna Carta for Disabled Persons',
    weight: 1.25,
  },
  {
    sourceId: 'ra-10070',
    targetId: 'ra-7277',
    type: 'implements',
    label: 'PDAO local implementation mechanism for Magna Carta for Disabled Persons services',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10070',
    targetId: 'ra-7160',
    type: 'workflow_related_to',
    label: 'PDAO services and local government service-delivery coordination',
    weight: 1,
  },
  {
    sourceId: 'ra-10524',
    targetId: 'ra-7277',
    type: 'amends',
    label: 'PWD employment and reserved-position amendments to disability-rights framework',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10524',
    targetId: 'pd-442',
    type: 'workflow_related_to',
    label: 'PWD employment safeguards and general labor standards relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-10754',
    targetId: 'ra-7277',
    type: 'amends',
    label: 'Expanded PWD benefits and privileges amendments to disability-rights framework',
    weight: 1.25,
  },
  {
    sourceId: 'ra-10754',
    targetId: 'ra-9442',
    type: 'workflow_related_to',
    label: 'PWD discount, VAT-exemption, and privilege workflow relationship',
    weight: 1.05,
  },
  {
    sourceId: 'ra-10172',
    targetId: 'ra-9048',
    type: 'amends',
    label: 'Civil registry correction expansion',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10022',
    targetId: 'ra-8042',
    type: 'amends',
    label: 'Migrant worker protection amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11211',
    targetId: 'ra-7653',
    type: 'amends',
    label: 'BSP charter amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11898',
    targetId: 'ra-9003',
    type: 'amends',
    label: 'EPR Act amendments to ecological solid waste framework',
    weight: 1.2,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-7653',
    type: 'workflow_related_to',
    label: 'Payment-system supervision under BSP charter',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-11211',
    type: 'workflow_related_to',
    label: 'Payment systems and BSP financial-stability powers',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-9160',
    type: 'workflow_related_to',
    label: 'Payment-system operations and AML monitoring coordination',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10168',
    type: 'workflow_related_to',
    label: 'Payment rails and CFT screening coordination',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-8484',
    type: 'workflow_related_to',
    label: 'Payment systems and access-device fraud evidence',
    weight: 1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-12010',
    type: 'workflow_related_to',
    label: 'Payment systems and financial-account scam handling',
    weight: 1,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-11765',
    type: 'workflow_related_to',
    label: 'Payment services and financial-consumer complaint handling',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10175',
    type: 'workflow_related_to',
    label: 'Payment platforms and cybercrime evidence coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11127',
    targetId: 'ra-10173',
    type: 'workflow_related_to',
    label: 'Payment-system records privacy safeguards',
    weight: 0.95,
  },
  {
    sourceId: 'ra-10168',
    targetId: 'ra-9160',
    type: 'cross_references',
    label: 'CFT controls share AMLC reporting framework',
    weight: 1.2,
  },
  {
    sourceId: 'ra-10168',
    targetId: 'ra-11479',
    type: 'workflow_related_to',
    label: 'CFT asset-freeze and anti-terrorism designation coordination',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-10173',
    type: 'workflow_related_to',
    label: 'Anti-terrorism watchlist and incident records privacy safeguards',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-10175',
    type: 'workflow_related_to',
    label: 'Anti-terrorism referrals and cybercrime evidence coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-4200',
    type: 'cross_references',
    label: 'Surveillance and communications-interception safeguards',
    weight: 1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'constitution-1987',
    type: 'requires',
    label: 'Bill of Rights due-process safeguards for anti-terrorism actions',
    weight: 1,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'rules-criminal-procedure',
    type: 'workflow_related_to',
    label: 'Criminal procedure safeguards for anti-terrorism enforcement',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11479',
    targetId: 'ra-9745',
    type: 'workflow_related_to',
    label: 'Custodial and human-rights safeguards for detention or interrogation',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11647',
    targetId: 'ra-7042',
    type: 'amends',
    label: 'Foreign investment liberalization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11595',
    targetId: 'ra-8762',
    type: 'amends',
    label: 'Retail trade liberalization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-12021',
    targetId: 'ra-10635',
    type: 'cross_references',
    label: 'Seafarer welfare and STCW credential relationship',
    weight: 1,
  },
  {
    sourceId: 'ra-9295',
    targetId: 'ra-9993',
    type: 'workflow_related_to',
    label: 'Domestic shipping safety and Coast Guard incident coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-9295',
    targetId: 'pd-857',
    type: 'workflow_related_to',
    label: 'Domestic shipping and port-operation coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'Downstream oil market monitoring under DOE energy mandate',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'LPG industry regulation and DOE energy oversight',
    weight: 1.1,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-7638',
    type: 'workflow_related_to',
    label: 'Biofuels program and DOE energy policy coordination',
    weight: 1.1,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-8479',
    type: 'workflow_related_to',
    label: 'Biofuel blends in downstream petroleum product workflows',
    weight: 1,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-8479',
    type: 'workflow_related_to',
    label: 'LPG retail and refilling within downstream fuel controls',
    weight: 0.95,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-7394',
    type: 'workflow_related_to',
    label: 'Fuel retail consumer complaint and product-disclosure coordination',
    weight: 0.9,
  },
  {
    sourceId: 'ra-11592',
    targetId: 'ra-7394',
    type: 'workflow_related_to',
    label: 'LPG product safety and consumer complaint coordination',
    weight: 0.95,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-9513',
    type: 'workflow_related_to',
    label: 'Biofuels and renewable-energy policy relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'ra-10667',
    type: 'workflow_related_to',
    label: 'Deregulated downstream oil market and competition-risk review',
    weight: 0.85,
  },
  {
    sourceId: 'ra-8479',
    targetId: 'pd-1586',
    type: 'workflow_related_to',
    label: 'Fuel facilities and environmental impact screening coordination',
    weight: 0.85,
  },
  {
    sourceId: 'ra-9367',
    targetId: 'ra-8749',
    type: 'workflow_related_to',
    label: 'Biofuel blend claims and air-quality coordination',
    weight: 0.85,
  },
  {
    sourceId: 'ra-9369',
    targetId: 'ra-8436',
    type: 'amends',
    label: 'Automated election modernization amendments',
    weight: 1.1,
  },
  {
    sourceId: 'ra-11573',
    targetId: 'pd-1529',
    type: 'amends',
    label: 'Imperfect-title confirmation and land-registration relationship',
    weight: 1,
  },
  {
    sourceId: 'ra-11573',
    targetId: 'ra-10023',
    type: 'workflow_related_to',
    label: 'Public land title confirmation and residential free-patent workflow',
    weight: 1,
  },
  {
    sourceId: 'ra-11573',
    targetId: 'ra-11231',
    type: 'workflow_related_to',
    label: 'Public land title confirmation and agricultural free-patent workflow',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11231',
    targetId: 'ra-6657',
    type: 'workflow_related_to',
    label: 'Agricultural free-patent transfer must be separated from CARP restrictions',
    weight: 0.9,
  },
  {
    sourceId: 'ra-9700',
    targetId: 'ra-6657',
    type: 'amends',
    label: 'CARPER amendments to comprehensive agrarian reform framework',
    weight: 1.15,
  },
  {
    sourceId: 'ra-11953',
    targetId: 'ra-6657',
    type: 'workflow_related_to',
    label: 'Agrarian emancipation and ARB relief within CARP workflows',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11953',
    targetId: 'ra-9700',
    type: 'workflow_related_to',
    label: 'ARB debt condonation and CARPER implementation relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11642',
    targetId: 'ra-11222',
    type: 'workflow_related_to',
    label: 'Administrative adoption and simulated-birth rectification relationship',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11642',
    targetId: 'ra-11767',
    type: 'workflow_related_to',
    label: 'Alternative child care and foundling recognition relationship',
    weight: 1.05,
  },
  {
    sourceId: 'ra-11642',
    targetId: 'ra-7610',
    type: 'workflow_related_to',
    label: 'Adoption and child-protection intake relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11222',
    targetId: 'act-3753',
    type: 'workflow_related_to',
    label: 'Simulated-birth rectification and civil-registry record relationship',
    weight: 1,
  },
  {
    sourceId: 'ra-11222',
    targetId: 'ra-10172',
    type: 'workflow_related_to',
    label: 'Simulated-birth rectification must be separated from ordinary civil-registry corrections',
    weight: 0.85,
  },
  {
    sourceId: 'ra-11767',
    targetId: 'act-3753',
    type: 'workflow_related_to',
    label: 'Foundling recognition and birth-registration relationship',
    weight: 1,
  },
  {
    sourceId: 'ra-11767',
    targetId: 'ra-10173',
    type: 'workflow_related_to',
    label: 'Foundling identity records and privacy safeguards relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-11642',
    targetId: 'eo-209-1987',
    type: 'workflow_related_to',
    label: 'Adoption and family-status relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-10930',
    targetId: 'ra-4136',
    type: 'amends',
    label: 'Driver license validity amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-11976',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'Ease of Paying Taxes updates to the tax code',
    weight: 1,
  },
  {
    sourceId: 'ra-12023',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'VAT on digital services amendments to the tax code',
    weight: 1.15,
  },
  {
    sourceId: 'bir-rr-2025-03',
    targetId: 'ra-12023',
    type: 'implements',
    label: 'BIR implementing regulations for VAT on digital services',
    weight: 1.25,
  },
  {
    sourceId: 'bir-rmc-2025-47',
    targetId: 'ra-12023',
    type: 'agency_guidance_for',
    label: 'BIR digital services VAT circular guidance',
    weight: 1.1,
  },
  {
    sourceId: 'ra-12023',
    targetId: 'ra-11976',
    type: 'workflow_related_to',
    label: 'Digital services VAT and EOPT invoicing workflow relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-12023',
    targetId: 'ra-11967',
    type: 'workflow_related_to',
    label: 'Digital services VAT and internet transaction platform workflow relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-12023',
    targetId: 'ra-8792',
    type: 'workflow_related_to',
    label: 'Digital services VAT and e-commerce record workflow relationship',
    weight: 0.85,
  },
  {
    sourceId: 'ra-10963',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'TRAIN tax code amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-11534',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'CREATE tax code amendments',
    weight: 1,
  },
  {
    sourceId: 'ra-12066',
    targetId: 'ra-8424',
    type: 'amends',
    label: 'CREATE MORE tax incentive updates',
    weight: 1,
  },
  {
    sourceId: 'ra-4726',
    targetId: 'pd-957',
    type: 'workflow_related_to',
    label: 'Condominium ownership and buyer-protection workflow relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-4726',
    targetId: 'ra-9904',
    type: 'workflow_related_to',
    label: 'Condominium governance and association-record workflow relationship',
    weight: 0.85,
  },
  {
    sourceId: 'bp-220',
    targetId: 'ra-7279',
    type: 'workflow_related_to',
    label: 'Economic or socialized housing standards and urban housing workflow relationship',
    weight: 0.95,
  },
  {
    sourceId: 'bp-220',
    targetId: 'ra-11201',
    type: 'workflow_related_to',
    label: 'Socialized housing standards and DHSUD governance workflow relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-10912',
    targetId: 'ra-8981',
    type: 'requires',
    label: 'CPD records support PRC license renewal and professional regulation workflows',
    weight: 1,
  },
  {
    sourceId: 'ra-10918',
    targetId: 'ra-8981',
    type: 'workflow_related_to',
    label: 'Pharmacy practice and PRC professional regulation workflow relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-10918',
    targetId: 'ra-9711',
    type: 'workflow_related_to',
    label: 'Pharmacy dispensing and FDA health-product regulation workflow relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-9502',
    targetId: 'ra-10918',
    type: 'workflow_related_to',
    label: 'Medicine access and pharmacy dispensing workflow relationship',
    weight: 0.9,
  },
  {
    sourceId: 'ra-9502',
    targetId: 'ra-8293',
    type: 'workflow_related_to',
    label: 'Medicine access and intellectual-property workflow relationship',
    weight: 0.75,
  },
  {
    sourceId: 'ra-10643',
    targetId: 'ra-9211',
    type: 'workflow_related_to',
    label: 'Graphic health warnings and tobacco regulation workflow relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-10643',
    targetId: 'ra-11900',
    type: 'workflow_related_to',
    label: 'Tobacco warning and vaporized nicotine product workflow relationship',
    weight: 0.8,
  },
  {
    sourceId: 'ra-12022',
    targetId: 'ra-10863',
    type: 'workflow_related_to',
    label: 'Agricultural economic sabotage and customs import evidence workflow relationship',
    weight: 0.95,
  },
  {
    sourceId: 'ra-12022',
    targetId: 'ra-10611',
    type: 'workflow_related_to',
    label: 'Agricultural economic sabotage and food-safety traceability workflow relationship',
    weight: 0.85,
  },
  {
    sourceId: 'ra-12022',
    targetId: 'ra-7581',
    type: 'workflow_related_to',
    label: 'Agricultural economic sabotage and price-monitoring workflow relationship',
    weight: 0.8,
  },
  {
    sourceId: 'eo-209-1987',
    targetId: 'ra-386',
    type: 'cross_references',
    label: 'Family Code and Civil Code private-law relationship',
    weight: 0.9,
  },
]

const FRAMEWORK_RELATIONS: LocalAuthorityRelation[] = COMPLIANCE_FRAMEWORKS.flatMap((framework) => (
  framework.lawIds.flatMap((sourceId) => (
    framework.lawIds
      .filter((targetId) => targetId !== sourceId)
      .map((targetId) => ({
        sourceId,
        targetId,
        type: 'workflow_related_to' as const,
        label: framework.title,
        weight: 0.45,
      }))
  ))
))

function relationKey(relation: LocalAuthorityRelation) {
  return `${relation.sourceId}:${relation.type}:${relation.targetId}:${relation.label}`
}

export const AUTHORITY_RELATIONS: LocalAuthorityRelation[] = [
  ...CURATED_RELATIONS,
  ...FRAMEWORK_RELATIONS,
].filter((relation, index, relations) => (
  relations.findIndex((candidate) => relationKey(candidate) === relationKey(relation)) === index
))
