import type { LocalComplianceFramework } from './types'

export const COMPLIANCE_FRAMEWORKS: LocalComplianceFramework[] = [
  {
    id: 'data-incident-response',
    title: 'Data, Cyber, and Mobile Incident Response Stack',
    triggers: [
      'data breach',
      'breach response',
      'cyber incident',
      'phishing',
      'account compromise',
      'account takeover',
      'unauthorized access',
      'social engineering',
      'sim fraud',
      'mobile number fraud',
      'identity data',
      'personal data',
      'privacy controls',
      'health records',
      'private image',
      'takedown',
    ],
    lawIds: [
      'ra-10173',
      'ra-10175',
      'ra-11934',
      'ra-8792',
      'ra-9995',
      'ra-11930',
      'ra-11055',
      'ra-12010',
      'ra-10844',
      'ra-12254',
    ],
    summary:
      'Use this when a workflow involves personal data, online accounts, electronic evidence, SIM or mobile-number abuse, identity records, or image/video evidence.',
    sequence: [
      'Classify the incident, affected data, system, account, subscriber, or media type before choosing the response path.',
      'Preserve evidence and logs without over-sharing personal data or private images.',
      'Assign breach, cybercrime, telco, privacy, and victim-support owners instead of routing everything to one generic help desk.',
      'Use lawful referral, disclosure, takedown, and notification steps with records of who approved each action.',
    ],
    checkpoints: [
      'Privacy notice, lawful basis, data minimization, retention, access control, and breach response ownership are stated.',
      'Incident reports preserve audit logs, screenshots, messages, account activity, or media evidence with chain-of-custody controls.',
      'SIM, PhilSys, subscriber, biometric, or private-image data has stricter access and disclosure controls.',
      'User support includes correction, complaint, escalation, and non-disclosure safeguards.',
    ],
  },
  {
    id: 'financial-account-scam-response',
    title: 'Financial Account Scam, Mule Account, and Wallet Fraud Stack',
    triggers: [
      'financial account scam',
      'money mule',
      'mule account',
      'wallet scam',
      'account takeover',
      'social engineering',
      'phishing',
      'unauthorized transfer',
      'scam proceeds',
    ],
    lawIds: ['ra-12010', 'ra-11765', 'ra-9160', 'ra-8484', 'ra-10175', 'ra-10173'],
    summary:
      'Use this when a workflow involves mule accounts, financial-account scams, phishing, social-engineering fraud, wallet scams, unauthorized transfers, account takeover, suspicious transactions, or scam evidence.',
    sequence: [
      'Classify the report as mule-account use, account takeover, phishing, social-engineering fraud, unauthorized transfer, AML concern, payment-access-device issue, cybercrime, or privacy incident.',
      'Map scam intake, customer notice, account hold or freeze route, suspicious transaction escalation, evidence custody, remediation, and regulator or law-enforcement referral.',
      'Separate customer support from compliance investigation, AML reporting, cybercrime referral, financial-consumer remediation, and privacy-safe records handling.',
      'Preserve transaction logs, account records, device or IP data, messages, complaint files, and disclosure approvals with retention and access controls.',
    ],
    checkpoints: [
      'Fraud intake, customer notice, account action, investigation, escalation, and remediation owners are named.',
      'Mule-account, phishing, account-takeover, suspicious-transaction, and unauthorized-transfer paths are not collapsed into one generic complaint flow.',
      'Evidence is preserved with chain of custody, privacy limits, authorized disclosure, and regulator or law-enforcement coordination.',
    ],
  },
  {
    id: 'digital-government-and-public-ict',
    title: 'Digital Government, E-Governance, and Public ICT Stack',
    triggers: [
      'digital government',
      'e-governance',
      'egovernance',
      'government portal',
      'online government service',
      'government data exchange',
      'interoperability',
      'dict',
      'ict system',
      'public ict',
      'digital public service',
    ],
    lawIds: ['ra-12254', 'ra-10844', 'ra-8792', 'ra-10173', 'ra-10175', 'ra-9470', 'eo-2-2016', 'ra-11032'],
    summary:
      'Use this when public offices move services, records, payments, permits, benefits, or data exchange into digital channels.',
    sequence: [
      'Classify the digital service: portal, permit, benefit, payment, record request, data exchange, identity or access workflow, or ICT infrastructure.',
      'Map legal authority, service owner, system owner, data owner, security owner, helpdesk, fallback path, and records custodian.',
      'Separate authentication, privacy, cybersecurity, records retention, FOI or disclosure, accessibility, continuity, procurement, and user-support controls.',
      'Preserve audit logs, change records, incident reports, data-sharing approvals, retention schedules, and user complaint records.',
    ],
    checkpoints: [
      'Digital services identify accountable offices, service standards, authentication, accessibility, continuity, and offline assistance.',
      'Inter-agency data exchange states lawful basis, purpose, access, retention, correction, and incident handling.',
      'ICT projects include cybersecurity, procurement, records, FOI, privacy, and user-support dependencies before launch.',
    ],
  },
  {
    id: 'ai-governance-privacy-public-sector-automation',
    title: 'AI Governance, Privacy, and Public-Sector Automation Stack',
    triggers: [
      'ai governance',
      'artificial intelligence',
      'ai system',
      'automated decision',
      'automated decision making',
      'algorithmic decision',
      'chatbot',
      'government ai',
      'public sector ai',
      'public-sector automation',
      'model governance',
      'privacy impact assessment',
      'human review',
      'ai policy',
      'ai tool',
    ],
    lawIds: [
      'npc-advisory-2024-04',
      'ra-10173',
      'sc-ai-governance-framework-2026',
      'ra-12254',
      'ra-10844',
      'ra-10175',
      'ra-8792',
      'ra-11032',
    ],
    summary:
      'Use this when AI, chatbots, automated decisions, or model-assisted public services involve personal data, public-sector workflows, courts, records, or citizen-facing services.',
    sequence: [
      'Classify the AI use case, users, data inputs, outputs, affected persons, and whether it supports or influences official decisions.',
      'Map privacy, cybersecurity, records, transparency, human review, accessibility, complaint, and service-continuity controls before deployment.',
      'Separate model developer, system operator, personal information controller, processor, public-service owner, and human decision owner.',
      'Keep testing, consultation, audit, monitoring, incident response, data retention, and vendor-access records tied to the authority for the service.',
    ],
    checkpoints: [
      'AI processing identifies lawful basis, purpose, data sources, retention, prompt or log handling, and data-subject rights.',
      'Human review, appeal, correction, complaint, and escalation paths are stated for decisions or public services affected by AI.',
      'Governance covers fairness, accountability, transparency, privacy, cybersecurity, monitoring, audit, and bias or accuracy review.',
      'Public-sector AI services remain accessible through non-digital or assisted channels when required for citizen service delivery.',
    ],
  },
  {
    id: 'lgu-permit-and-service-delivery',
    title: 'LGU Ordinance, Permit, and Service Delivery Stack',
    triggers: [
      'barangay ordinance',
      'municipal ordinance',
      'business permit',
      'clearance',
      'license',
      'citizen charter',
      'processing time',
      'local fee',
      'public hearing',
      'local service',
      'e-governance',
      'digital service',
      'online government service',
      'government portal',
    ],
    lawIds: ['ra-7160', 'ra-11032', 'ra-12009', 'ra-10667', 'ra-10173', 'ra-12254', 'ra-10844'],
    summary:
      'Use this when a city, municipality, province, or barangay creates rules, fees, services, permits, digital channels, procurement steps, or citizen-facing application workflows.',
    sequence: [
      'Start with LGU authority, approving body, public hearing or publication, and consistency with national law.',
      'Map each citizen-facing service to a receiving office, documentary checklist, fees, processing time, written decision route, and digital or offline service path.',
      'If procurement or exclusive suppliers are involved, separate procurement safeguards from ordinary permit controls.',
      'Check privacy, cybersecurity, accessibility, and records controls whenever resident, business, health, financial, identity, or complaint data is collected.',
    ],
    checkpoints: [
      'The ordinance states legal basis, scope, responsible office, standards, procedure, monitoring, budget, effectivity, and appeal path.',
      'Permits and clearances do not allow open-ended extra requirements after filing.',
      'Fees, fines, supplier preferences, and license conditions have authority, objective criteria, and due process.',
      'Digital services, records, reports, and citizen data have retention, access, fallback, and service-continuity controls.',
    ],
  },
  {
    id: 'barangay-justice-and-local-complaint-routing',
    title: 'Barangay Justice and Local Complaint Routing Stack',
    triggers: [
      'barangay complaint',
      'barangay dispute',
      'barangay conciliation',
      'katarungang pambarangay',
      'lupon',
      'pangkat',
      'amicable settlement',
      'certificate to file action',
      'blotter',
      'neighborhood dispute',
      'local mediation',
    ],
    lawIds: ['ra-7160', 'ra-9285', 'ra-10173', 'ra-9344', 'ra-9262', 'rules-criminal-procedure'],
    summary:
      'Use this when an LGU or barangay handles local disputes, lupon or pangkat conciliation, barangay complaint intake, settlement records, certificate-to-file-action routing, or referrals to courts, police, social welfare, or agencies.',
    sequence: [
      'Classify whether the matter is a covered barangay dispute, excluded criminal/protection/urgent matter, administrative complaint, child case, VAWC concern, or ordinary service request.',
      'Map complainant, respondent, barangay, lupon chair, pangkat members, notice route, appearance schedule, settlement record, non-settlement record, and certificate-to-file-action owner.',
      'Separate conciliation from police blotter, child protection, VAWC referral, criminal complaint, civil case, privacy records, and ADR or court-supervised mediation.',
      'Preserve summons, minutes, settlement terms, certificates, referrals, evidence, and authorized disclosures with confidentiality and retention controls.',
    ],
    checkpoints: [
      'Complaint intake states coverage, exceptions, venue, parties, notice, schedule, appearance, settlement, non-settlement, certificate, and referral rules.',
      'Sensitive child, family, health, address, violence, criminal, or personal-data records have privacy, access, redaction, and retention safeguards.',
      'High-risk matters are routed to police, prosecutor, court, DSWD, women and children desk, or other authority rather than forced into ordinary barangay conciliation.',
    ],
  },
  {
    id: 'public-accountability-and-government-funds',
    title: 'Public Accountability, Ethics, Audit, and Government Funds Stack',
    triggers: [
      'graft',
      'corruption',
      'conflict of interest',
      'saln',
      'gift',
      'coa audit',
      'public funds',
      'cash advance',
      'liquidation',
      'disbursement',
      'plunder',
      'gocc',
      'salary grade',
      'honorarium',
      'allowance',
      'civil service',
      'administrative case',
      'administrative discipline',
      'appointment',
      'promotion',
      'personnel action',
      'public-private partnership',
      'public private partnership',
      'ppp',
      'concession',
      'unsolicited proposal',
    ],
    lawIds: [
      'ra-3019',
      'ra-6713',
      'pd-1445',
      'ra-7080',
      'ra-10149',
      'ra-6758',
      'ra-12009',
      'ra-11966',
      'ra-11032',
      'ra-7160',
      'eo-292-1987',
      'pd-807',
    ],
    summary:
      'Use this when public officers, public funds, PPPs, concessions, official discretion, supplier or beneficiary selection, GOCCs, compensation, civil service, personnel actions, gifts, conflicts, liquidation, or COA audit exposure overlap.',
    sequence: [
      'Classify the public action: official decision, procurement, PPP or concession, grant, permit, disbursement, cash advance, asset custody, GOCC board action, personnel action, administrative discipline, or compensation item.',
      'Map authority, decision maker, conflict checks, beneficiary or supplier criteria, supporting documents, approval thresholds, accountable officer, and audit route.',
      'Separate ethics, anti-graft, audit, PPP approval, procurement, service delivery, civil service, public compensation, GOCC governance, privacy, and criminal-escalation issues.',
      'Preserve evidence such as approvals, vouchers, receipts, liquidation reports, conflict disclosures, SALN or financial-interest records, appointment papers, service records, board minutes, and complaints.',
    ],
    checkpoints: [
      'Decision makers, approving bodies, accountable officers, and reviewers are named with segregation of duties.',
      'Conflicts, gifts, private interests, supplier or beneficiary preferences, and unwarranted-benefit risks have disclosure, recusal, and complaint controls.',
      'Public funds, cash advances, payments, grants, assets, and compensation items have authority, support documents, liquidation, retention, and COA audit trails.',
      'Civil-service appointments, promotions, details, reassignments, discipline, and appeals preserve merit, eligibility, notice, record, privacy, and review controls.',
      'PPP or concession projects include approval route, value-for-money review, risk allocation, performance monitoring, and public accountability records.',
      'High-value or repeated transactions have escalation, evidence preservation, and independent review for serious corruption or plunder-risk indicators.',
    ],
  },
  {
    id: 'public-personnel-appointment-and-discipline',
    title: 'Public Personnel Appointment and Discipline Stack',
    triggers: [
      'civil service',
      'civil service commission',
      'csc',
      'administrative case',
      'administrative discipline',
      'personnel action',
      'government appointment',
      'public employee',
      'government employee',
      'reassignment',
      'detail',
      'promotion',
      'preventive suspension',
      'service record',
      'appointing authority',
    ],
    lawIds: ['pd-807', 'eo-292-1987', 'ra-6713', 'ra-6758', 'ra-10173', 'ra-9470'],
    summary:
      'Use this when a public office handles appointments, promotions, reassignment, detail, separation, administrative discipline, suspension, personnel files, service records, or Civil Service Commission-facing actions.',
    sequence: [
      'Classify the personnel event: appointment, promotion, detail, reassignment, transfer, separation, complaint, investigation, preventive suspension, formal charge, decision, or appeal.',
      'Map appointing authority, qualification and eligibility basis, HR owner, deciding officer, records custodian, notice route, hearing or answer period, and appeal path.',
      'Separate merit and fitness review, ethics or conflict issues, compensation classification, personnel-record custody, privacy, and archive or retention duties.',
      'Preserve appointment papers, qualification proofs, service records, notices, answers, hearing records, decisions, appeal records, and authorized disclosures.',
    ],
    checkpoints: [
      'Appointments or promotions identify position, eligibility, qualification standard, appointing authority, funding or plantilla basis, and personnel-record owner.',
      'Discipline or suspension workflows include complaint intake, investigation, notice, formal charge, answer, hearing or review, written decision, penalty basis, appeal, and anti-retaliation controls.',
      'Personnel files, service records, health or family documents, performance records, complaint records, and disciplinary files have privacy, access, redaction, retention, and archive rules.',
    ],
  },
  {
    id: 'employee-benefits-and-social-insurance',
    title: 'Employee Benefits, Leave, and Social Insurance Stack',
    triggers: [
      'employee benefits',
      'payroll benefits',
      'sss',
      'social security',
      'gsis',
      'pag ibig',
      'pag-ibig',
      'philhealth',
      'employer contribution',
      'premium contribution',
      'maternity leave',
      'paternity leave',
      'kasambahay',
      'domestic worker',
      'household helper',
      'retirement benefit',
      'service charge',
      'lactation',
      'breastfeeding',
    ],
    lawIds: [
      'ra-11199',
      'ra-8291',
      'ra-9679',
      'ra-10606',
      'ra-11210',
      'ra-8187',
      'ra-10361',
      'ra-11360',
      'ra-10028',
      'pd-442',
      'ra-10173',
    ],
    summary:
      'Use this when a workflow touches private or government employment benefits, payroll contributions, service charges, SSS, GSIS, Pag-IBIG, PhilHealth, maternity or paternity leave, lactation support, household employment, or benefit records.',
    sequence: [
      'Classify the worker or member first: private employee, government employee, household worker, self-employed member, dependent, or leave claimant.',
      'Map mandatory membership, contribution or premium basis, remittance owner, benefit eligibility, documentary proof, claim route, and correction process.',
      'Separate payroll, service-charge distribution, SSS, GSIS, Pag-IBIG, PhilHealth, maternity leave, paternity leave, lactation support, kasambahay, labor-standard, and privacy controls.',
      'Protect payroll, service-charge, contribution, health, pregnancy, breastfeeding, family, service-record, household-employment, dependent, and benefit-claim records with role-based access and retention.',
    ],
    checkpoints: [
      'Covered workers, employers, household employers, dependents, contribution basis, remittance deadlines, and records owners are identified.',
      'Leave and benefit workflows state eligibility, notice, documentary proof, benefit/payment treatment, decision timeline, denial reason, and grievance or correction path.',
      'SSS, GSIS, Pag-IBIG, PhilHealth, service-charge, maternity, paternity, lactation, and kasambahay requirements are not collapsed into a generic benefits clause.',
      'Health, pregnancy, breastfeeding, payroll, service, family, and benefit records have confidentiality, privacy, retention, and authorized-disclosure safeguards.',
    ],
  },
  {
    id: 'workplace-pay-flex-work-and-family-support',
    title: 'Workplace Pay, Flexible Work, and Family Support Stack',
    triggers: [
      'telecommuting',
      'remote work',
      'work from home',
      'hybrid work',
      'flexible work',
      'service charge',
      'minimum wage',
      'wage order',
      'regional wage',
      'lactation',
      'breastfeeding',
      'nursing mother',
    ],
    lawIds: ['pd-442', 'ra-11165', 'ra-11360', 'ra-6727', 'ra-10028', 'ra-11210', 'ra-11058', 'ra-10173'],
    summary:
      'Use this when workplace policies combine pay rules, remote or flexible work, service-charge sharing, wage-order compliance, and family or lactation support.',
    sequence: [
      'Classify the work arrangement and pay issue: onsite, telecommuting, hybrid, service-charge eligible, minimum-wage covered, lactation support, or leave-related.',
      'Map covered workers, schedule, wage or service-charge computation, equipment and safety responsibility, facility or accommodation owner, payroll records, and grievance path.',
      'Separate remote-work monitoring, labor standards, wage orders, service charges, occupational safety, lactation facilities, privacy, and payroll records.',
      'Preserve agreements, payroll computations, service-charge distributions, wage-order basis, accommodation requests, monitoring data, and complaint records.',
    ],
    checkpoints: [
      'Telecommuting or hybrid work states voluntary agreement, hours, performance, equipment, safety, monitoring, privacy, and equal-treatment rules.',
      'Wage and service-charge workflows identify covered employees, computation method, payout timing, payroll owner, records, and DOLE escalation.',
      'Breastfeeding or lactation support includes facility, break period, hygiene, privacy, scheduling, complaint, and record safeguards.',
    ],
  },
  {
    id: 'environmental-operations',
    title: 'Environmental Operations and Facility Controls Stack',
    triggers: [
      'environmental compliance',
      'wastewater',
      'solid waste',
      'hazardous waste',
      'air emission',
      'protected area',
      'buffer zone',
      'chemical spill',
      'energy audit',
      'facility compliance',
    ],
    lawIds: ['ra-9003', 'ra-9275', 'ra-8749', 'ra-6969', 'ra-11038', 'ra-11285'],
    summary:
      'Use this when a facility, LGU, business, school, event, tourism site, or public building touches waste, water, emissions, chemicals, protected areas, or energy use.',
    sequence: [
      'Classify the activity first: solid waste, wastewater, air emissions, hazardous substances, protected-area use, or energy management.',
      'Identify the regulator and local role before assigning inspection or penalty powers.',
      'Separate prevention, monitoring, corrective action, reporting, emergency response, and penalties.',
      'Track permits, sampling, manifests, reports, audits, and disposal or restoration records.',
    ],
    checkpoints: [
      'Waste streams, discharge points, emission sources, chemicals, land-use zones, and energy baselines are identified.',
      'DENR, EMB, PAMB, DOE, LGU, or barangay roles are not collapsed into one generic enforcement office.',
      'Monitoring includes frequency, responsible office, evidence records, corrective action, and public or regulator reporting.',
      'Penalties or shutdowns include notice, correction, hearing, and appeal safeguards.',
    ],
  },
  {
    id: 'environmental-impact-wildlife-and-forestry',
    title: 'Environmental Impact, Wildlife, and Forestry Controls Stack',
    triggers: [
      'environmental impact assessment',
      'environmental impact statement',
      'eis',
      'ecc',
      'environmental compliance certificate',
      'environmentally critical project',
      'environmentally critical area',
      'wildlife permit',
      'threatened species',
      'biodiversity impact',
      'habitat',
      'tree cutting',
      'timber transport',
      'forest land',
      'forestry permit',
      'watershed',
    ],
    lawIds: [
      'pd-1586',
      'ra-9147',
      'pd-705',
      'ra-11038',
      'ra-9275',
      'ra-8749',
      'ra-6969',
      'ra-9003',
      'ra-8371',
      'ra-7160',
    ],
    summary:
      'Use this when a project, facility, land-use action, tourism site, infrastructure work, tree cutting, habitat disturbance, or resource activity may need environmental impact review, ECC conditions, wildlife safeguards, forestry controls, and LGU coordination.',
    sequence: [
      'Classify the activity and site first: environmentally critical project, environmentally critical area, protected area, forest land, watershed, wildlife habitat, ordinary facility, or local land-use action.',
      'Map project proponent, DENR/EMB, PAMB, forestry or wildlife authority, LGU, affected communities, indigenous-community consent, and records owners before approval.',
      'Separate ECC or environmental assessment from pollution permits, protected-area clearance, wildlife permits, forestry permits, local business/building permits, and land-title checks.',
      'Preserve EIS or IEE records, ECC conditions, monitoring reports, species or tree inventories, transport papers, consultations, mitigation actions, restoration proof, and enforcement records.',
    ],
    checkpoints: [
      'Project screening identifies environmentally critical project or area, affected resource, site boundary, regulator, permit route, consultation, and monitoring cadence.',
      'Wildlife, habitat, forest land, tree cutting, timber transport, watershed, protected-area, and pollution issues are not collapsed into one generic environmental clause.',
      'ECC conditions, mitigation measures, restoration obligations, compliance monitoring, corrective action, and reporting owners are named.',
      'Community consultation, FPIC screening, complaint routing, and public-record handling are addressed where people or indigenous communities may be affected.',
    ],
  },
  {
    id: 'built-environment-and-public-facilities',
    title: 'Built Environment, Sanitation, Accessibility, and Public Facilities Stack',
    triggers: [
      'building permit',
      'occupancy permit',
      'renovation',
      'public facility',
      'sanitary permit',
      'food establishment',
      'market sanitation',
      'accessibility',
      'contractor license',
      'licensed contractor',
      'architect',
      'civil engineer',
      'electrical engineer',
      'mechanical engineer',
      'master plumber',
      'signed plans',
      'sealed plans',
      'public toilet',
      'event venue',
    ],
    lawIds: [
      'pd-1096',
      'ra-4566',
      'ra-9266',
      'ra-544',
      'ra-7920',
      'ra-8495',
      'ra-1378',
      'pd-856',
      'bp-344',
      'ra-7277',
      'ra-9514',
      'ra-11058',
      'ra-11032',
    ],
    summary:
      'Use this when a building, public facility, food establishment, event venue, school, market, clinic, transport point, or service desk needs physical safety, professional design, licensed contractor, sanitation, accessibility, and public-health controls.',
    sequence: [
      'Classify the facility: construction, occupancy, food handling, public service, event, transport, workplace, or accessible public space.',
      'Map building permits, professional plans and seals, contractor licensing, occupancy, fire safety, sanitation, accessibility, OSH, service delivery, and complaint controls before use.',
      'Separate design approval, licensed professional responsibility, contractor execution, inspections, staff certificates, facility maintenance, correction orders, and closure or stop-use procedures.',
      'Document responsible officials, inspection evidence, compliance deadlines, and public-facing assistance channels.',
    ],
    checkpoints: [
      'Building permit, occupancy, fire, sanitation, accessibility, contractor, design professional, and safety responsibilities are assigned.',
      'Architectural, civil/structural, electrical, mechanical, and plumbing work is tied to the appropriate licensed professional and signed/sealed plan records.',
      'Contractor license, work scope, project supervision, inspections, change orders, completion proof, and complaint records are retained.',
      'Food, water, toilet, sewage, refuse, pest-control, and public-facility sanitation controls are not collapsed into generic cleanliness rules.',
      'PWD access is built into the facility and workflow, not handled only by ad hoc staff assistance.',
      'Correction, closure, appeal, and reopening rules are stated for failed inspections or unsafe facilities.',
    ],
  },
  {
    id: 'land-climate-coastal-and-resource-governance',
    title: 'Land, Climate, Coastal, and Natural Resource Governance Stack',
    triggers: [
      'climate action plan',
      'coastal resource',
      'municipal waters',
      'fishing permit',
      'quarry',
      'mining',
      'protected area',
      'renewable energy project',
      'land use',
      'environmental permit',
    ],
    lawIds: ['ra-9729', 'ra-8550', 'ra-7942', 'ra-11038', 'ra-9513', 'ra-9275', 'ra-8749', 'ra-6969', 'ra-7160'],
    summary:
      'Use this when land use, climate planning, coastal livelihoods, fisheries, quarrying, mining, protected areas, renewable-energy projects, or environmental permitting overlap.',
    sequence: [
      'Classify the resource and jurisdiction: land, coastal water, protected area, mineral, energy resource, climate risk, or pollution source.',
      'Map LGU authority, national regulator, environmental permits, consultation, affected communities, monitoring, and rehabilitation or restoration duties.',
      'Separate resource access, livelihood support, conservation, enforcement, climate adaptation, extraction, and revenue or fee controls.',
      'Track evidence such as maps, permits, sampling, consultations, inspection reports, closure plans, and corrective actions.',
    ],
    checkpoints: [
      'Jurisdiction, resource boundary, permit type, regulator, consultation, and monitoring cadence are stated.',
      'Climate, DRRM, environmental, protected-area, fisheries, mining, and energy duties are not treated as one generic environmental clause.',
      'Community, fisherfolk, vulnerable-group, or affected-sector participation is documented where relevant.',
      'Rehabilitation, restoration, emergency response, penalties, and appeals are included for resource-impact activities.',
    ],
  },
  {
    id: 'mobility-land-agriculture-and-community-rights',
    title: 'Mobility, Land, Agriculture, and Community Rights Stack',
    triggers: [
      'traffic ordinance',
      'transport operator',
      'public utility',
      'land title',
      'property registration',
      'ancestral domain',
      'fpic',
      'agriculture support',
      'food safety',
      'organic agriculture',
      'farmers organization',
      'direct purchase',
      'sagip saka',
    ],
    lawIds: [
      'ra-4136',
      'ra-11659',
      'pd-1529',
      'ra-8371',
      'ra-8435',
      'ra-10068',
      'ra-10611',
      'ra-11321',
      'ra-7160',
      'ra-10173',
    ],
    summary:
      'Use this when a workflow touches road transport, public-service operation, land title or registry records, ancestral domains or FPIC, agricultural support, food safety, organic claims, or farmer and fisherfolk enterprise programs.',
    sequence: [
      'Classify the activity first: traffic enforcement, public-service operation, land or title transaction, ancestral-domain impact, farm support, food chain, organic claim, or farmer/fisherfolk enterprise.',
      'Map the public authority, regulator, registry, affected community, beneficiary group, inspection owner, records custodian, and appeal or grievance route.',
      'Separate LGU permits from national transport, public-service, land-registration, NCIP, agriculture, food-safety, and procurement controls.',
      'Track evidence such as licenses, titles, survey plans, FPIC records, beneficiary lists, inspection reports, traceability logs, purchase records, and complaints.',
    ],
    checkpoints: [
      'Vehicle, operator, public-service, land-title, beneficiary, food-chain, and community-consent scopes are not collapsed into generic permit language.',
      'Land and resource projects check title or registry records, ancestral-domain or FPIC issues, environmental impacts, and affected-community safeguards where relevant.',
      'Agriculture, food-safety, organic, and direct-purchase programs include eligibility, certification, traceability, inspection, conflict checks, and audit trail.',
      'Transport, land, farm, and community records have privacy, retention, redaction, and authorized-disclosure controls.',
    ],
  },
  {
    id: 'road-safety-driver-and-vehicle-compliance',
    title: 'Road Safety, Driver, and Vehicle Compliance Stack',
    triggers: [
      'road safety',
      'driver license',
      'license renewal',
      'vehicle registration',
      'seat belt',
      'seatbelt',
      'motorcycle helmet',
      'helmet law',
      'drunk driving',
      'drugged driving',
      'distracted driving',
      'mobile phone while driving',
      'child car seat',
      'child restraint',
      'traffic accident',
      'traffic violation',
      'lto',
    ],
    lawIds: ['ra-4136', 'ra-10930', 'ra-8750', 'ra-10054', 'ra-10586', 'ra-10913', 'ra-11229', 'ra-11659', 'ra-10173'],
    summary:
      'Use this when a workflow touches driver licensing, vehicle records, traffic enforcement, seat belts, motorcycle helmets, DUI checks, distracted-driving controls, child restraints, accident records, or LTO-facing road-safety programs.',
    sequence: [
      'Classify the road-safety issue first: driver license, vehicle registration, seat-belt duty, motorcycle helmet, drunk/drugged driving, distracted driving, child restraint, accident response, or operator regulation.',
      'Map covered vehicles, drivers, passengers, children, riders, operators, enforcement office, LTO/LTFRB/DTI coordination, evidence source, notice, penalty, appeal route, and record custodian.',
      'Separate safety-device standards, driver fitness, traffic citations, health or toxicology data, child passenger information, employer fleet discipline, and public-service permits.',
      'Verify current LTO, LTFRB, DTI, and enforcement rules before relying on fixed forms, fees, citation steps, or device standards.',
    ],
    checkpoints: [
      'Driver and vehicle scope, authority, enforcement office, evidence rules, notices, penalties, and appeals are stated.',
      'Seat-belt, helmet, child-restraint, drunk/drugged-driving, distracted-driving, and ordinary traffic rules are handled as distinct duties.',
      'License, medical, toxicology, child passenger, citation, accident, photo, video, and vehicle records have privacy, retention, correction, and disclosure safeguards.',
      'Fleet, school, LGU, or public-service transport workflows coordinate local enforcement with national regulator duties and public-safety education.',
    ],
  },
  {
    id: 'critical-utilities-energy-telecom-and-water-services',
    title: 'Critical Utilities, Energy, Telecom, and Water Services Stack',
    triggers: [
      'electric utility',
      'electricity distribution',
      'power distribution',
      'power interruption',
      'electricity bill',
      'distribution utility',
      'electric cooperative',
      'telecommunications',
      'telecom operator',
      'broadband',
      'internet service provider',
      'network outage',
      'spectrum',
      'water district',
      'water utility',
      'water service',
      'water connection',
      'water disconnection',
      'public utility',
      'critical infrastructure',
    ],
    lawIds: [
      'ra-11659',
      'ra-9136',
      'ra-7925',
      'pd-198-water-districts',
      'ra-9513',
      'ra-11285',
      'ra-11934',
      'ra-11765',
      'ra-10667',
      'ra-10173',
      'ra-9275',
      'pd-856',
    ],
    summary:
      'Use this when electricity, telecom, internet, broadband, water-district, or utility-like services need operator classification, regulator coordination, rates, continuity, outage, customer-service, and records controls.',
    sequence: [
      'Classify the utility service: electric generation, transmission, distribution, supply, telecom network, internet access, spectrum use, water district, or water-service customer workflow.',
      'Map the operator, regulator, franchise or certificate route, tariff or rate basis, service area, outage or interruption owner, complaint channel, and regulatory-reporting cadence.',
      'Separate public-service classification, sector-specific regulator duties, consumer complaint handling, privacy, competition, environmental, sanitation, and ordinary local-permit controls.',
      'Retain service applications, contracts, meter or subscriber records, billing, outage logs, disconnection notices, complaints, repairs, regulator filings, and incident records with privacy safeguards.',
    ],
    checkpoints: [
      'Public-utility or critical-infrastructure status, operator role, regulator, authorization path, and service area are identified.',
      'Rates, bills, connection, disconnection, interruptions, complaints, refunds or remedies, and accessibility of service are documented.',
      'Electricity, telecom, water, renewable-energy, energy-efficiency, SIM, privacy, competition, and consumer-protection duties are not merged into one generic utility clause.',
      'Customer, subscriber, meter, outage, network, billing, and complaint records have access, retention, correction, and authorized-disclosure controls.',
    ],
  },
  {
    id: 'tourism-hospitality-events-and-travel-services',
    title: 'Tourism, Hospitality, Events, and Travel Services Stack',
    triggers: [
      'tourism',
      'tourist',
      'hotel',
      'resort',
      'guesthouse',
      'lodging',
      'homestay',
      'short-term rental',
      'travel agency',
      'tour operator',
      'tour guide',
      'tourist transport',
      'visitor safety',
      'guest registration',
      'dot accreditation',
      'tourism accreditation',
      'tourism enterprise',
      'event venue',
    ],
    lawIds: [
      'ra-9593',
      'ra-7160',
      'pd-856',
      'ra-9514',
      'bp-344',
      'ra-7277',
      'ra-7394',
      'ra-11360',
      'ra-11038',
      'pd-1586',
      'ra-10173',
      'ra-11967',
    ],
    summary:
      'Use this when a hotel, resort, homestay, event venue, travel agency, tour operator, tour guide, tourist transport, visitor program, or tourism site needs accreditation, permits, safety, guest-record, complaint, refund, environmental, accessibility, and service-standard controls.',
    sequence: [
      'Classify the service first: accommodation, travel booking, tour operation, guide service, tourist transport, event venue, protected-area tourism, or local tourism promotion.',
      'Map DOT or local tourism-office accreditation, LGU permits, sanitation, fire safety, accessibility, consumer disclosures, refund route, guest-record custody, and incident response.',
      'Separate guest safety, environmental or protected-area approvals, service-charge payroll, online booking records, customer complaints, and ordinary business licensing.',
      'Preserve accreditation, permits, room or booking logs, guest registration, incident reports, complaints, refund records, safety inspections, and privacy notices.',
    ],
    checkpoints: [
      'Tourism enterprise type, regulator, accreditation or permit route, responsible office, and renewal cadence are stated.',
      'Guest safety, sanitation, fire safety, accessibility, protected-area or environmental screening, and emergency response are not handled as generic business-permit items.',
      'Prices, inclusions, restrictions, cancellation, refund, complaint, and escalation routes are clear before booking or guest intake.',
      'Guest identities, booking records, incident reports, payments, complaints, and travel details have privacy, retention, access, and authorized-disclosure controls.',
    ],
  },
  {
    id: 'consumer-finance-and-commerce',
    title: 'Consumer, Financial, Commerce, AML, and Tax Stack',
    triggers: [
      'consumer complaint',
      'product warranty',
      'wallet fraud',
      'payment collection',
      'loan',
      'remittance',
      'kyc',
      'suspicious transaction',
      'invoice',
      'receipt',
      'vat',
      'withholding',
      'tax return',
      'nirc',
      'national internal revenue code',
      'train law',
      'create act',
      'create more',
      'tax incentives',
      'corporate income tax',
      'online sale',
      'price freeze',
      'basic necessities',
      'bmbe',
      'msme',
      'bank secrecy',
      'online marketplace',
      'e-marketplace',
      'digital platform',
      'online merchant',
      'internet transaction',
    ],
    lawIds: [
      'ra-7394',
      'ra-11967',
      'ra-11765',
      'ra-12010',
      'ra-9160',
      'ra-1405',
      'ra-7581',
      'ra-9178',
      'ra-9501',
      'ra-8792',
      'ra-10173',
      'ra-11976',
      'ra-8424',
      'ra-10963',
      'ra-11534',
      'ra-12066',
    ],
    summary:
      'Use this when a workflow involves consumer sales, online marketplaces, internet transactions, financial products, financial-account scams, payments, remittance, AML controls, bank records, price controls, MSME support, e-commerce records, invoicing, or taxpayer-facing collections.',
    sequence: [
      'Identify whether the issue is consumer product/service quality, internet transaction, marketplace platform, financial consumer protection, financial-account scam, AML monitoring, e-commerce evidence, tax, or privacy.',
      'Map disclosures, seller identity, fees, complaints, refunds, fraud reports, KYC, transaction reports, bank-record access, price controls, incentives, invoices, receipts, and record retention.',
      'Separate customer service handling from regulator escalation, suspicious transaction reporting, and tax documentation.',
      'Avoid collecting financial or identity data without clear purpose, access controls, and retention period.',
    ],
    checkpoints: [
      'Terms, fees, risks, warranties, price, complaint route, and remedy are clear before the transaction.',
      'Online merchants, marketplaces, and digital platforms have seller verification, buyer notice, redress, takedown, dispute, and record-retention controls.',
      'Unauthorized transactions, fraud reports, and suspicious transaction workflows have timelines and responsible officers.',
      'Money-mule, social-engineering, phishing, account-takeover, and financial-account-scam reports have evidence custody, hold or freeze routing, and regulator or law-enforcement escalation.',
      'Bank deposit, price monitoring, BMBE, and MSME records are handled with eligibility, confidentiality, and audit safeguards.',
      'Invoices, receipts, VAT, withholding, and tax records are accounted for where payment collection is involved.',
      'Financial and consumer records are protected with privacy, confidentiality, and audit safeguards.',
    ],
  },
  {
    id: 'business-tax-registration-invoicing-and-incentives',
    title: 'Business Tax Registration, Invoicing, and Incentives Stack',
    triggers: [
      'tax',
      'taxpayer',
      'bir',
      'nirc',
      'national internal revenue code',
      'tax code',
      'invoice',
      'receipt',
      'vat',
      'withholding',
      'withholding tax',
      'tax return',
      'percentage tax',
      'income tax',
      'corporate income tax',
      'excise tax',
      'train law',
      'create act',
      'create more',
      'tax incentives',
      'registered business enterprise',
      'investment promotion agency',
      'peza',
      'boi',
      'eopt',
    ],
    lawIds: ['ra-8424', 'ra-11976', 'ra-10963', 'ra-11534', 'ra-12066', 'ra-9178', 'ra-9501', 'ra-10863', 'ra-10173'],
    summary:
      'Use this when a workflow touches BIR registration, invoices or receipts, tax returns, VAT, withholding, income tax, percentage tax, excise tax, corporate tax, or business tax incentives.',
    sequence: [
      'Classify the taxpayer and activity: individual, sole proprietor, corporation, MSME/BMBE, registered business enterprise, payment collector, withholding agent, importer, seller, or service provider.',
      'Map BIR registration, books and records, invoice or receipt workflow, tax type, filing and payment owner, rate or threshold assumptions, supporting documents, and retention period.',
      'Separate base NIRC duties, EOPT invoicing and taxpayer-rights rules, TRAIN-amended tax treatment, CREATE/CREATE MORE incentives, customs duties, privacy handling, and local permits.',
      'Verify current BIR forms, revenue regulations, filing deadlines, rates, thresholds, and incentive guidance before implementation.',
    ],
    checkpoints: [
      'Taxpayer classification, BIR registration, books of account, invoices or receipts, returns, payment route, and retention owner are stated.',
      'Income tax, VAT, percentage tax, excise tax, and withholding are separated where the transaction may trigger more than one tax treatment.',
      'CREATE or CREATE MORE incentive workflows identify the registered business enterprise, IPA/FIRB route, incentive period, conditions, reports, and audit evidence.',
      'Payment, payroll, platform, or collection workflows preserve invoices, receipts, withholding certificates, returns, proof of payment, notices, and BIR correspondence.',
    ],
  },
  {
    id: 'banking-lending-insurance-and-financial-institutions',
    title: 'Banking, Lending, Insurance, and Financial Institutions Stack',
    triggers: [
      'bsp',
      'bangko sentral',
      'central bank',
      'bank supervision',
      'financial stability',
      'banking',
      'bank loan',
      'bank director',
      'lending company',
      'loan app',
      'financing company',
      'lease financing',
      'factoring',
      'insurance',
      'insurance claim',
      'pre need',
      'pre-need',
      'planholder',
      'pdic',
      'deposit insurance',
      'closed bank',
    ],
    lawIds: [
      'ra-7653',
      'ra-11211',
      'ra-8791',
      'ra-9474',
      'ra-8556',
      'ra-10607',
      'ra-9829',
      'ra-10846',
      'ra-9160',
      'ra-1405',
      'ra-11765',
      'ra-12010',
      'ra-9510',
      'ra-10173',
    ],
    summary:
      'Use this when a workflow touches BSP-supervised activity, banking, loans, lending companies, financing companies, insurance, pre-need plans, deposit insurance, borrower data, or depositor and policyholder records.',
    sequence: [
      'Classify the financial activity first: BSP-supervised entity, bank operation, lending company, financing company, insurance, pre-need plan, PDIC/deposit-insurance claim, AML process, financial-account scam, credit reporting, or financial consumer complaint.',
      'Map license or authority, responsible compliance owner, disclosure, pricing or premium terms, customer eligibility, complaint and dispute route, regulator escalation, and record custodian.',
      'Separate prudential supervision, market conduct, AML, bank secrecy, credit reporting, consumer complaints, policy claims, borrower collections, and data privacy.',
      'Escalate high-risk activity involving deposits, bank officers, borrower harassment, insurance-like promises, planholder funds, closed banks, suspicious transactions, mule accounts, account takeovers, or regulatory examinations.',
    ],
    checkpoints: [
      'Entity type, regulator, license or authority, product terms, disclosures, fees or premiums, and responsible office are stated.',
      'Borrower, depositor, policyholder, planholder, and beneficiary records have access, confidentiality, retention, correction, and authorized-disclosure controls.',
      'Complaints, fraud reports, claims, collection disputes, and regulatory reports have timelines, evidence custody, and escalation owners.',
      'Bank secrecy, AML, credit reporting, financial consumer protection, and data privacy are treated as separate but coordinated controls.',
    ],
  },
  {
    id: 'payments-credit-evidence-and-dispute-resolution',
    title: 'Payments, Credit, Evidence, and Dispute Resolution Stack',
    triggers: [
      'payment fraud',
      'access device',
      'credit card fraud',
      'unauthorized transaction',
      'wiretapping',
      'recorded conversation',
      'bouncing check',
      'dishonored check',
      'credit report',
      'credit score',
      'insolvency',
      'rehabilitation',
      'arbitration',
      'mediation',
      'dispute resolution',
    ],
    lawIds: ['ra-8484', 'ra-12010', 'ra-4200', 'bp-22', 'ra-9510', 'ra-10142', 'ra-9285', 'ra-11765', 'ra-10173', 'ra-8792'],
    summary:
      'Use this when a workflow touches card or access-device fraud, financial-account scams, unauthorized payments, recorded communications, bounced checks, credit reports, distressed debt, insolvency, mediation, arbitration, or dispute evidence.',
    sequence: [
      'Classify the issue first: access-device fraud, financial-account scam, communication recording, check dishonor, credit reporting, financial distress, or ADR/dispute handling.',
      'Map authority, consent or authorization, notice, documentary proof, evidence custody, dispute intake, correction or cure path, and escalation route.',
      'Separate payment fraud, money-mule screening, privacy, bank or credit information, consumer remediation, criminal referral, civil collection, insolvency, and ADR safeguards.',
      'Preserve transaction logs, checks, notices, recordings, credit files, creditor claims, settlement communications, and decisions with retention and confidentiality controls.',
    ],
    checkpoints: [
      'Payment, recording, credit, insolvency, and dispute workflows state who may collect, review, share, correct, retain, or escalate evidence.',
      'Unauthorized transactions, access-device issues, mule accounts, account takeover, bounced checks, and credit-report disputes include intake, proof, investigation, timelines, and correction or cure routes.',
      'Recording or communication-monitoring workflows include consent or lawful authority, minimization, restricted access, retention, and chain-of-custody safeguards.',
      'ADR and insolvency paths do not bypass safety, criminal, labor, consumer, creditor, court, or regulator escalation when formal process is required.',
    ],
  },
  {
    id: 'civil-documents-family-and-claims',
    title: 'Civil Documents, Family Status, Evidence, and Small Claims Stack',
    triggers: [
      'civil code',
      'contract',
      'civil liability',
      'damages',
      'marriage certificate',
      'birth certificate',
      'civil registry',
      'civil registrar',
      'family support',
      'custody',
      'notarized affidavit',
      'notary',
      'evidence',
      'small claims',
      'money claim',
      'debt collection',
    ],
    lawIds: [
      'ra-386',
      'eo-209-1987',
      'act-3753',
      'ra-9048',
      'ra-10172',
      'am-02-8-13-sc',
      'rules-of-court-evidence',
      'am-08-8-7-sc',
      'ra-10173',
      'ra-8792',
      'ra-9285',
    ],
    summary:
      'Use this when a workflow touches contracts, civil liability, family status, birth or marriage records, civil registry corrections, notarized affidavits, evidence handling, small money claims, or debt-collection records.',
    sequence: [
      'Classify the matter first: contract or obligation, family status, civil registry record, correction petition, notarized document, evidence file, or small money claim.',
      'Map parties, authority, proof, civil registrar or notary role, record custodian, correction route, claim amount, evidence source, and privacy controls.',
      'Separate civil remedies from criminal threats, administrative actions, privacy duties, family protection, ADR, small claims, and ordinary customer support.',
      'Preserve contracts, certificates, IDs, affidavits, registry annotations, notices, demand letters, official records, and evidence logs with custody and retention rules.',
    ],
    checkpoints: [
      'Contracts identify parties, authority, consent, object, cause or consideration, performance, breach, notice, remedies, and records.',
      'Civil registry and family-status workflows identify the certificate, registrar, requester authority, proof, correction or annotation path, confidentiality, and downstream record updates.',
      'Notarized documents and evidence files include personal appearance or identity checks, authentication, custodian, chain of custody, retention, and authorized disclosure.',
      'Small-claims and debt workflows state amount basis, proof, demand, venue or filing route, settlement handling, privacy-safe collection conduct, and records custody.',
    ],
  },
  {
    id: 'rights-criminal-enforcement-and-public-order',
    title: 'Rights, Criminal Enforcement, Public Order, and Custody Stack',
    triggers: [
      'bill of rights',
      'due process',
      'criminal complaint',
      'police report',
      'search warrant',
      'arrest',
      'theft',
      'estafa',
      'falsification',
      'libel',
      'juvenile',
      'dangerous drugs',
      'drug testing',
      'firearms',
      'public assembly',
      'rally permit',
      'custody',
      'detention',
      'torture',
    ],
    lawIds: [
      'constitution-1987',
      'act-3815',
      'rules-criminal-procedure',
      'ra-9344',
      'ra-9165-drugs',
      'ra-10591',
      'bp-880',
      'ra-9745',
      'rules-of-court-evidence',
      'ra-10173',
      'ra-7160',
    ],
    summary:
      'Use this when a workflow touches criminal complaints, police reports, searches, arrests, evidence, custody, minors in conflict with the law, dangerous drugs, firearms, public assemblies, detention, or rights-sensitive enforcement.',
    sequence: [
      'Classify the action: regulatory inspection, complaint intake, administrative discipline, criminal referral, search, arrest, custody, juvenile handling, public assembly, drug/firearm incident, or human-rights complaint.',
      'Map legal authority, rights notice, receiving office, objective criteria, warrant or exception, affidavit or evidence requirements, custody owner, referral route, timeline, and appeal or review path.',
      'Separate civil, administrative, barangay, school, workplace, police, prosecutor, court, social welfare, and human-rights channels.',
      'Preserve affidavits, incident reports, warrants, evidence inventories, custody logs, medical records, child records, drug-test or lab records, firearm inventories, public-assembly permits, and notices with strict access and retention controls.',
    ],
    checkpoints: [
      'Enforcement powers identify legal basis, due process, notice or rights information, objective standards, responsible office, written decision, records, and review path.',
      'Criminal complaints, searches, arrests, and evidence files include affidavits, probable-cause or warrant route, custody, chain-of-custody, privacy, and authorized referral.',
      'Minor, drug, firearm, public assembly, detention, and torture-risk workflows include specialized safeguards instead of generic incident handling.',
      'Policies avoid public shaming, coercion, arbitrary detention, warrantless access, viewpoint-based restrictions, and unsupported criminal labels.',
    ],
  },
  {
    id: 'business-market-entry-ownership-and-secured-finance',
    title: 'Business Market Entry, Ownership, Cooperative, and Secured Finance Stack',
    triggers: [
      'business registration',
      'foreign investment',
      'foreign equity',
      'foreign investor',
      'retail trade',
      'foreign retailer',
      'cooperative',
      'cda',
      'cooperative members',
      'secured transaction',
      'security interest',
      'collateral',
      'movable property',
      'startup',
      'paid up capital',
      'market entry',
    ],
    lawIds: [
      'ra-9520',
      'ra-7042',
      'ra-11647',
      'ra-8762',
      'ra-11595',
      'ra-11057',
      'ra-11232',
      'ra-11032',
      'ra-11976',
      'ra-11765',
      'ra-8792',
      'ra-10173',
    ],
    summary:
      'Use this when a workflow touches market entry, foreign ownership, retail trade, cooperative formation, member governance, secured lending, movable collateral, business registration, customer-facing sales, or investor records.',
    sequence: [
      'Classify the business structure and activity: corporation, cooperative, domestic market enterprise, export enterprise, foreign retailer, e-commerce seller, lender, or secured-credit arrangement.',
      'Map ownership, nationality or foreign-equity restrictions, regulator, registration route, capitalization, permits, tax registration, customer obligations, privacy controls, and periodic reporting.',
      'For cooperatives, map CDA registration, bylaws, member rights, board and committee duties, capital, audit, surplus, and general assembly decisions.',
      'For secured transactions, map debtor, secured creditor, collateral, security agreement, perfection, notice registry, priority, enforcement, release, and debtor-record protection.',
    ],
    checkpoints: [
      'Market-entry workflows do not collapse foreign investment, retail, corporation, cooperative, tax, local permit, consumer, and privacy duties into one generic business permit step.',
      'Foreign investment and retail workflows document activity classification, ownership, capital, registration, regulator filing, and updated rule review.',
      'Cooperative workflows include member governance, bylaws, board/committee roles, audit, capital, surplus handling, dispute route, and CDA records.',
      'Secured finance workflows include collateral description, security agreement, registry/perfection, priority, enforcement, release, debtor privacy, and audit trail.',
    ],
  },
  {
    id: 'immigration-citizenship-passports-and-overseas-filipino-records',
    title: 'Immigration, Citizenship, Passports, and Overseas Filipino Records Stack',
    triggers: [
      'immigration',
      'visa',
      'foreign national',
      'alien',
      'overstay',
      'deportation',
      'passport',
      'travel document',
      'dual citizenship',
      'citizenship reacquisition',
      'naturalization',
      'administrative naturalization',
      'ofw',
      'migrant worker',
      'department of migrant workers',
      'overseas employment',
    ],
    lawIds: [
      'ca-613',
      'ra-11983',
      'ra-8239',
      'ra-9225',
      'ca-473',
      'ra-9139',
      'ra-11641',
      'ra-8042',
      'ra-10022',
      'ra-10173',
      'act-3753',
      'ra-8792',
    ],
    summary:
      'Use this when a workflow touches foreign nationals, immigration status, visas, admission, deportation, passport or travel-document handling, dual citizenship, naturalization, overseas Filipino workers, or DMW-facing records.',
    sequence: [
      'Classify the matter first: immigration admission or stay, visa or alien registration, passport or travel document, dual-citizenship reacquisition, naturalization, OFW deployment, or DMW assistance.',
      'Map the responsible agency, eligibility or status basis, proof documents, filing route, notice or hearing path, oath or certificate where relevant, and records custodian.',
      'Separate passport, immigration, citizenship, naturalization, civil registry, overseas employment, trafficking, labor, tax, and benefits decisions instead of treating identity documents as interchangeable.',
      'Protect passports, visas, biometrics, citizenship evidence, birth records, oath records, employment contracts, repatriation files, and complaint records with strict access, retention, and authorized-disclosure controls.',
    ],
    checkpoints: [
      'Immigration workflows identify status, visa or stay basis, responsible office, notice, hearing or appeal route, and record custody.',
      'Passport workflows use current passport authority, citizenship proof, applicant authority, minor safeguards, issuance or renewal path, cancellation or loss process, and DFA or consular record controls.',
      'Citizenship and naturalization workflows distinguish retention or re-acquisition, judicial naturalization, administrative naturalization, oath, certificate, civil registry, and passport consequences.',
      'OFW and DMW workflows document agency verification, contract and fee controls, illegal-recruitment reporting, welfare, repatriation, legal assistance, and confidentiality safeguards.',
    ],
  },
  {
    id: 'elections-civic-participation-and-youth-governance',
    title: 'Elections, Civic Participation, Campaigns, and Youth Governance Stack',
    triggers: [
      'election',
      'comelec',
      'candidate',
      'campaign',
      'campaign material',
      'political advertisement',
      'voter registration',
      'voter list',
      'soce',
      'automated election',
      'vote counting',
      'source code review',
      'sangguniang kabataan',
      'sk funds',
      'youth council',
      'barangay election',
    ],
    lawIds: [
      'bp-881',
      'ra-8189',
      'ra-7166',
      'ra-9006',
      'ra-8436',
      'ra-9369',
      'ra-10742',
      'ra-11768',
      'ra-7160',
      'ra-10173',
      'ra-3019',
      'pd-1445',
      'ra-9470',
    ],
    summary:
      'Use this when a workflow touches COMELEC processes, voter registration, campaign materials, political ads, campaign finance, election returns, automated election systems, barangay or SK elections, SK funds, or youth governance records.',
    sequence: [
      'Classify the matter first: voter registration, candidate activity, campaign material, campaign finance, election-day or canvassing record, automated election system, complaint or offense, or SK/youth-governance program.',
      'Map responsible office, election period, COMELEC or registration-board route, eligible actor, required proof, prohibited acts, reporting owner, complaint route, and records custodian.',
      'Separate campaign activity, public-service announcements, government resources, procurement, public funds, voter records, election technology, youth programs, and ordinary barangay services.',
      'Protect voter records, campaign approvals, contribution and expenditure files, election returns, canvass records, technology logs, source-code review records, SK budget records, and youth participant data with access and retention controls.',
    ],
    checkpoints: [
      'Voter-registration workflows include eligibility, registration-board action, precinct or locality, objection, deactivation or reactivation, notice, and record-custody controls.',
      'Campaign workflows include campaign period, material classification, sponsor disclosure, spending records or SOCE owner, public-resource neutrality, takedown or complaint process, and retention.',
      'Election operations and automated election systems include custody, watcher or audit access, transmission or canvassing safeguards, incident handling, security, and evidence preservation.',
      'SK and youth-governance workflows include eligibility, youth development plan, training, fund authority, procurement, reporting, grievance, privacy, and audit safeguards.',
    ],
  },
  {
    id: 'workplace-school-and-public-safety',
    title: 'Workplace, School, Public Safety, and Protection Stack',
    triggers: [
      'workplace safety',
      'labor standards',
      'wage policy',
      'telecommuting',
      'remote work',
      'work from home',
      'service charge',
      'wage order',
      'lactation',
      'breastfeeding',
      'age discrimination',
      'mental health',
      'sexual harassment',
      'safe spaces',
      'bullying',
      'student safety',
      'child online safety',
      'osaec',
      'csaem',
      'fire safety',
      'evacuation',
      'disaster plan',
      'internet cafe',
    ],
    lawIds: [
      'pd-442',
      'ra-11165',
      'ra-11360',
      'ra-6727',
      'ra-10028',
      'ra-11058',
      'ra-10911',
      'ra-11036',
      'ra-11313',
      'ra-9710',
      'ra-7877',
      'ra-10627',
      'ra-9775',
      'ra-11930',
      'ra-9514',
      'ra-10121',
    ],
    summary:
      'Use this when policies protect workers, students, minors, complainants, establishments, or the public from labor, safety, mental-health, harassment, fire, disaster, or online exploitation risks.',
    sequence: [
      'Classify the protected group and setting: workplace, school, public space, online platform, establishment, health support channel, or emergency site.',
      'Assign prevention, reporting, investigation, confidentiality, referral, corrective action, and emergency response owners.',
      'Separate discipline, labor relations, pay rules, telecommuting, accommodations, health support, victim protection, due process, and recordkeeping.',
      'Coordinate with the correct public office or authority when risks involve minors, fire safety, disasters, or law enforcement.',
    ],
    checkpoints: [
      'Policy includes reporting channels, responsible office, confidentiality, non-retaliation, due process, records, and accommodation where relevant.',
      'Safety and labor controls include classification, working conditions, wage or service-charge handling, telecommuting, training, drills, PPE or equipment, incident reports, inspections, and emergency escalation.',
      'Child, student, or victim data is protected and referral is limited to authorized channels.',
      'Sanctions do not replace prevention, support, correction, and appeal procedures.',
    ],
  },
  {
    id: 'health-welfare-and-accessibility',
    title: 'Health, Welfare, Accessibility, and Protection Stack',
    triggers: [
      'health service',
      'primary care',
      'mental health',
      'senior citizen',
      'pwd',
      'disability',
      'pwd accessibility',
      'reasonable accommodation',
      'child protection',
      'protection order',
      'vawc',
      'women',
      'gender equality',
      'trafficking',
      'social welfare',
    ],
    lawIds: ['ra-11223', 'ra-11036', 'ra-9994', 'ra-7277', 'bp-344', 'ra-7610', 'ra-9262', 'ra-9710', 'ra-10364', 'ra-11930', 'ra-10173'],
    summary:
      'Use this when a policy handles health services, vulnerable-person support, benefits, accessibility, protection orders, victim referral, or sensitive welfare records.',
    sequence: [
      'Classify the person served and risk: patient, senior citizen, PWD, child, VAWC complainant, trafficking victim, or general beneficiary.',
      'Map eligibility, consent, confidentiality, referral, emergency support, responsible office, and complaint or appeal route.',
      'Separate service delivery, benefit verification, protection, law-enforcement referral, health care, and data custody.',
      'Limit sensitive records to the purpose, role, retention period, and authorized disclosure route stated in the policy.',
    ],
    checkpoints: [
      'Eligibility, service owner, referral route, consent, confidentiality, and record retention are stated.',
      'Benefits or support services include accessible channels and reasonable accommodation where needed.',
      'Victim, child, health, senior, PWD, and welfare records receive stricter privacy and disclosure controls.',
      'Emergency or protection actions do not expose complainants, patients, or beneficiaries to retaliation or public disclosure.',
    ],
  },
  {
    id: 'public-health-disease-reporting-and-sensitive-health-records',
    title: 'Public Health, Disease Reporting, and Sensitive Health Records Stack',
    triggers: [
      'public health',
      'notifiable disease',
      'outbreak',
      'epidemic',
      'contact tracing',
      'quarantine',
      'tobacco',
      'smoking',
      'vape',
      'vapor product',
      'hiv',
      'aids',
      'immunization',
      'vaccination',
      'blood donation',
      'blood bank',
      'cancer',
      'cancer registry',
      'reproductive health',
      'family planning',
    ],
    lawIds: [
      'ra-11223',
      'ra-11332',
      'ra-9211',
      'ra-11900',
      'ra-11166',
      'ra-10152',
      'ra-7719',
      'ra-11215',
      'ra-10354',
      'ra-10173',
      'pd-856',
      'ra-9711',
    ],
    summary:
      'Use this when a workflow handles reportable diseases, outbreak response, tobacco or vape controls, HIV status, immunization, blood services, cancer care, reproductive health, or other sensitive public-health records.',
    sequence: [
      'Classify the health workflow first: disease surveillance, outbreak response, tobacco or vape regulation, HIV service, immunization, blood service, cancer care, reproductive health, or general health referral.',
      'Map reporting office, timeline, consent basis, confidentiality, referral, facility or agency coordination, responsible staff, complaint route, and record custodian.',
      'Separate clinical care, public-health surveillance, enforcement, school or workplace action, commercial sales, marketing claims, and privacy recordkeeping.',
      'Escalate high-risk disclosures, minors, infectious-disease events, HIV status, donor records, registry records, and reproductive-health counseling through authorized channels only.',
    ],
    checkpoints: [
      'Reportable events, service eligibility, responsible office, timeline, referral route, and complaint path are stated where relevant.',
      'Sensitive health records have purpose, consent or legal basis, access limits, authorized disclosure, retention, and correction or grievance controls.',
      'Tobacco and vape controls identify age restrictions, signage or warnings, sales channel, advertising review, enforcement owner, and recordkeeping.',
      'Health programs do not publish names, status, donor identity, HIV status, reproductive-health details, or registry data without authority and safeguards.',
    ],
  },
  {
    id: 'health-facility-emergency-care-and-patient-rights',
    title: 'Health Facility, Emergency Care, and Patient Rights Stack',
    triggers: [
      'hospital deposit',
      'anti hospital deposit',
      'no deposit',
      'emergency care',
      'emergency patient',
      'refusal to treat',
      'patient transfer',
      'hospital detention',
      'unpaid hospital bill',
      'patient discharge',
      'hospital license',
      'hospital licensure',
      'health facility',
      'medical clinic',
    ],
    lawIds: [
      'ra-10932',
      'ra-8344',
      'ra-9439',
      'ra-4226',
      'ra-11223',
      'ra-9711',
      'pd-856',
      'ra-10173',
      'ra-11036',
    ],
    summary:
      'Use this when a workflow touches hospital deposits, emergency treatment, refusal to treat, patient transfer, unpaid bills, discharge, detention, health-facility licensing, or patient records.',
    sequence: [
      'Classify the hospital issue: emergency triage, initial treatment, stabilization, transfer, admission, discharge, billing, detention risk, facility licensing, or patient-record handling.',
      'Map responsible clinical staff, billing or social-service staff, facility administrator, receiving facility, regulator-facing license or inspection owner, complaint route, and record custodian.',
      'Separate emergency care from payment collection, ordinary admission, discharge billing, medical-record release, PhilHealth or insurer claims, facility licensing, and privacy duties.',
      'Document triage, treatment, stabilization, transfer coordination, discharge order, bill, guarantee or promissory note, complaint, license, inspection, and corrective-action evidence.',
    ],
    checkpoints: [
      'Emergency assessment, stabilization, initial treatment, transfer, and complaint handling do not depend on deposit or advance payment.',
      'Discharge and patient release are separate from lawful billing, guarantee, collection, social-service assistance, and medical-record workflows.',
      'Hospital or clinic license status, service capability, inspection, patient-safety, sanitation, and corrective-action records are identified.',
      'Patient, billing, emergency, mental-health, and facility records have consent or legal basis, access limits, retention, and authorized-disclosure controls.',
    ],
  },
  {
    id: 'education-housing-records-and-benefits',
    title: 'Education, Housing, Records, and Social Benefits Stack',
    triggers: [
      'school records',
      'learner records',
      'scholarship',
      'student aid',
      'alternative learning',
      'foi request',
      'public records',
      'records retention',
      'socialized housing',
      'resettlement',
      '4ps',
      'solo parent',
      'child marriage',
      'cash assistance',
    ],
    lawIds: [
      'ra-10533',
      'ra-11510',
      'ra-10931',
      'ra-9470',
      'eo-2-2016',
      'ra-7279',
      'ra-11201',
      'ra-11310',
      'ra-11861',
      'ra-11596',
      'ra-10173',
      'ra-11032',
    ],
    summary:
      'Use this when a public-facing workflow handles education access, scholarships, learner records, FOI or archives, housing and resettlement, social assistance, solo-parent benefits, or child-protection-sensitive community services.',
    sequence: [
      'Classify the service first: learner support, tertiary subsidy, alternative learning, records access, housing or relocation, cash assistance, solo-parent benefit, or child-protection intake.',
      'Map eligibility, documentary proof, responsible office, timeline, benefit limits, privacy, records retention, grievance, appeal, and audit evidence.',
      'Separate benefit administration from public-record disclosure, child protection, school discipline, resettlement, payment handling, and ordinary customer service.',
      'Route sensitive learner, household, child, family, financial, health, and housing records through privacy and records-management controls.',
    ],
    checkpoints: [
      'Eligibility, documentary proof, receiving office, decision maker, timeline, denial reason, appeal or grievance path, and record owner are stated.',
      'School, scholarship, ALS, housing, 4Ps, solo-parent, and child-protection records have access, redaction, retention, and authorized-disclosure controls.',
      'FOI and archives workflows separate proactive disclosure, request handling, exceptions, redactions, denial notices, and preservation or disposal.',
      'Housing, relocation, and benefit decisions include consultation or validation where relevant and avoid discretionary selection without evidence.',
    ],
  },
  {
    id: 'real-estate-housing-buyer-and-tenant-protection',
    title: 'Real Estate, Housing Buyer, HOA, and Tenant Protection Stack',
    triggers: [
      'real estate',
      'property sale',
      'subdivision',
      'condominium',
      'condo',
      'license to sell',
      'contract to sell',
      'homeowners association',
      'hoa',
      'association dues',
      'rent control',
      'tenant',
      'lessor',
      'lessee',
      'residential lease',
      'maceda law',
      'installment buyer',
      'real estate broker',
      'real estate salesperson',
      'appraisal',
      'commission',
    ],
    lawIds: ['pd-957', 'ra-6552', 'ra-9904', 'ra-9653', 'ra-9646', 'ra-11201', 'pd-1529', 'ra-386', 'ra-10173'],
    summary:
      'Use this when a workflow involves subdivision or condominium buyers, real estate installment sales, homeowners associations, rent control, residential tenants, licensed real estate practitioners, or property transaction records.',
    sequence: [
      'Classify the matter first: subdivision or condominium project, installment sale, HOA governance, residential lease, broker/appraiser/salesperson service, title verification, or ordinary civil contract.',
      'Map project or property authority, license to sell, seller/developer/broker role, buyer or tenant notices, payment records, contract terms, title or registry evidence, complaint route, and records custodian.',
      'Separate buyer remedies, HOA governance, rent-control limits, Maceda-law cancellation/refund controls, professional licensing, title verification, tax, financing, and privacy records.',
      'Preserve contracts, receipts, notices, approved plans, licenses, association minutes, rental ledgers, title documents, appraisals, listing agreements, and complaint files.',
    ],
    checkpoints: [
      'Subdivision and condominium workflows include project registration, license to sell, approved plan, buyer disclosures, contract terms, receipts, title or turnover route, and complaint handling.',
      'Realty installment cancellation includes payment history, grace period, written notice, refund or cash-surrender computation, and dispute route.',
      'HOA and rent workflows include authority, bylaws or lease terms, dues or rent limits, notices, receipts, grievance path, and privacy-safe records.',
      'Real estate service workflows verify licensed broker, salesperson, appraiser, or consultant authority and keep listing, disclosure, commission, and complaint records.',
    ],
  },
  {
    id: 'ip-investment-and-regulated-products',
    title: 'IP, Investment, Health Product, and Market Claims Stack',
    triggers: [
      'copyright',
      'trademark',
      'software license',
      'brand use',
      'investment offer',
      'securities',
      'public offering',
      'health product',
      'fda registration',
      'product claim',
      'online sale',
    ],
    lawIds: ['ra-8293', 'ra-8799', 'ra-9711', 'ra-7394', 'ra-8792', 'ra-10173'],
    summary:
      'Use this when an app, campaign, product, marketplace, or public offer involves content ownership, brand use, investment claims, health products, advertising, or online sales.',
    sequence: [
      'Classify whether the issue is IP ownership, licensing, public investment, health-product regulation, consumer claim, e-commerce evidence, or privacy.',
      'Collect proof of license, registration, authorization, label, disclosure, risk warning, complaint route, and record owner before publishing.',
      'Separate marketing copy from legal disclosures, regulated claims, user-generated content, and complaint or takedown operations.',
      'Escalate high-risk health, investment, and infringement claims before launch rather than after customer complaints.',
    ],
    checkpoints: [
      'Brand, software, content, dataset, or creative work has ownership, license, attribution, and permitted-use evidence.',
      'Investment-like offers have registration, exemption, risk disclosure, suitability, advertising, and SEC review controls where relevant.',
      'Health-product claims have FDA registration, label, safety, adverse-event, recall, and complaint handling controls.',
      'Online claims preserve records, protect customer data, and provide correction, takedown, refund, or escalation paths.',
    ],
  },
  {
    id: 'aviation-maritime-ports-and-seafarer-operations',
    title: 'Aviation, Maritime, Ports, and Seafarer Operations Stack',
    triggers: [
      'maritime',
      'shipping',
      'domestic shipping',
      'vessel',
      'ship',
      'ferry',
      'port',
      'terminal',
      'cargo handling',
      'coast guard',
      'marine safety',
      'oil spill',
      'seafarer',
      'stcw',
      'manning agency',
      'seafarer welfare',
      'aviation',
      'aircraft',
      'airport',
      'air operator',
      'flight operations',
    ],
    lawIds: [
      'ra-9295',
      'ra-10635',
      'ra-9993',
      'ra-12021',
      'ra-9497',
      'pd-857',
      'ra-11659',
      'ra-11058',
      'ra-9514',
      'pd-856',
      'ra-10863',
      'ca-613',
      'ra-11983',
      'ra-10173',
    ],
    summary:
      'Use this when a workflow touches domestic shipping, ferries, ports, cargo handling, maritime safety, Coast Guard incidents, seafarer credentials and welfare, aircraft, airports, air operators, flight safety, or passenger and cargo transport records.',
    sequence: [
      'Classify the operation first: domestic shipping, port or terminal service, Coast Guard incident, seafarer credential or welfare process, air operator, airport or aircraft operation, customs-facing cargo, or passenger travel record.',
      'Map the regulator and owner for each slice: MARINA for shipping or STCW, PCG for maritime safety/security and pollution response, PPA for ports, CAAP for aviation, customs or immigration for cargo and travel interfaces, and privacy or labor owners for records.',
      'Separate operator authority, safety inspection, credential verification, passenger or cargo records, incident response, employment and welfare, and complaint or claims handling before approving a route, vessel, flight, port process, or crew workflow.',
      'Preserve certificates, manifests, cargo logs, voyage or flight records, crew and seafarer files, incident reports, inspection records, CCTV or communications logs, complaint records, and regulator filings.',
    ],
    checkpoints: [
      'Operator authorization, vessel/aircraft/facility identity, route or service scope, certificate status, responsible regulator, and accountable office are stated.',
      'Safety, inspection, emergency response, search and rescue, pollution or spill response, fire and sanitation dependencies, and incident notification are mapped to the correct authority.',
      'Seafarer or crew workflows verify STCW, employment contract, medical, wage, benefit, repatriation, grievance, and welfare controls before deployment or assignment.',
      'Passenger, cargo, crew, port, flight, incident, and travel records have privacy, retention, access, evidence, and authorized-disclosure controls.',
    ],
  },
  {
    id: 'imports-procurement-and-public-assets',
    title: 'Imports, Public Procurement, Assets, and Audit Stack',
    triggers: [
      'imported equipment',
      'customs declaration',
      'tariff',
      'public bidding',
      'supplier eligibility',
      'government contract',
      'asset disposal',
      'acceptance inspection',
      'procurement plan',
      'public-private partnership',
      'public private partnership',
      'ppp',
      'concession',
      'unsolicited proposal',
      'infrastructure project',
    ],
    lawIds: ['ra-10863', 'ra-12009', 'ra-11966', 'ra-11976', 'ra-10667', 'ra-7160'],
    summary:
      'Use this when public offices or regulated entities buy, import, classify, receive, inspect, award, dispose, partner through PPPs, or pay for goods, services, and infrastructure.',
    sequence: [
      'Separate customs import/export duties from procurement planning, PPP approval, and contract award duties.',
      'Define accountable office, valuation or approved budget, eligibility, inspection, acceptance, payment, tax, and audit records.',
      'Check competition, PPP risk allocation, value-for-money, and conflict-of-interest risks before creating preferred supplier, exclusive source, concession, or restricted eligibility rules.',
      'Preserve documents for post-clearance, PPP approval, procurement, acceptance, payment, and audit review.',
    ],
    checkpoints: [
      'Import or procurement workflows identify declaration, valuation, classification, permits, approved budget, and accountable officers.',
      'Supplier selection uses objective criteria and transparent documentation.',
      'PPP or contract implementation includes approval records, inspection, acceptance, performance standards, risk allocation, and audit trail.',
      'Payment, invoicing, tax, and asset records are kept separately from approval memos.',
    ],
  },
]
